torchgeo/torchgeo

torchgeo/datasets/gid15.py
torchgeo/datasets/levircd.py
torchgeo/datasets/patternnet.py

After building the docs, I noticed some issues in the docstrings, so this is an update for them. These aren't caught by pydocstyle which is interesting but seems to be more aesthetic.
Datasets changed: GID-15, LEVIR-CD+, and PatternNet.

Update Dataset docstrings

---

torchgeo/samplers/batch.py
torchgeo/samplers/single.py
torchgeo/samplers/utils.py

Two changes in sampler land: 
- Adds a `__len__` to GridGeoSampler
- Factors out the logic for sampling a random bounding box from the extent of another bounding box

Adding a length property to GridGeoSampler

---

docs/tutorials/getting_started.ipynb
test_chesapeakecvpr_models.py
tests/datasets/test_cbf.py
tests/datasets/test_cdl.py
tests/datasets/test_chesapeake.py
tests/transforms/test_transforms.py
torchgeo/datasets/chesapeake.py
torchgeo/datasets/geo.py
torchgeo/trainers/chesapeake.py
torchgeo/transforms/transforms.py
train.py

Working on several things explicit to ChesapeakeCVPR for paper benchmarking purposes:

Cleaning up ChesapeakeCVPR

---

tests/datasets/test_cdl.py
tests/datasets/test_utils.py
torchgeo/datasets/geo.py
torchgeo/datasets/utils.py

In #115, @calebrob6 noted that there is rarely intersection between the CDL dataset and any other dataset due to the way that indexing works for partial timestamps. This PR is an attempt to fix this issue.
The proposed behavior is as follows. For files with partial timestamps, the [mint, maxt] range should span all possible times within that range. For example:
* year only (e.g. CDL): first and last second of the year
* year, month only: first and last second of the month
* year, week only: first and last second of the week
* year, month, day only: first and last second of the day
* year, month, day, hour only: first and last second of the hour
* year, month, day, hour, min only: first and last second of the min
This should cover all possible [timestamp …

Proposal: better handling of partial timestamps

---

tests/datasets/test_cdl.py
torchgeo/datasets/cdl.py

This PR represents a first attempt to implement the behavior suggested in #99. Since this involves a lot of work and changes to the tests, I'm only doing this for CDL until we submit the paper. We can do this for other datasets later, but CDL was the biggest issue.
With this PR, the following issues no longer exist:
Note that we no longer test checksums when `download=False` (or data is already downloaded) and `checksum=True`. If we want to add that back, we'll need to parse the filename for the year and look up the md5 (not hard to do).

CDL: don't re-download dataset if zip files are missing

---

.github/workflows/docs.yaml
.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml

All of our GitHub Actions tests are required to pass in order for a PR to be merged. Previously, these tests were set up such that they would only be run depending on which files were modified. Unfortunately, GitHub doesn't seem to support [conditional required checks](https://github.community/t/feature-request-conditional-required-checks/16761). This PR changes the tests to run on every commit regardless of whether or not Python files were modified.

Required checks must always be run

---

tests/data/README.md

I followed the instructions [here](https://github.com/microsoft/torchgeo/tree/main/tests/data#vector-data) to create a vector test data (for SpaceNet) and ran into this error 
```
ValueError: Record does not match collection schema: odict_keys([]) != ['OBJECTID', 'partialDec', 'Shape_Leng', 'Id', 'OBJECTID_1', 'Shape_Area', 'partialBuilding', 'Shape_Le_1']
```
This is because dst is opened with src's meta. I was able to get around this issue by setting src properties to `OrderedDict()`.

Set src properties for vector test data generation

---

README.md
docs/index.rst
docs/user/installation.rst

I added a basic set of installation instructions for TorchGeo. Some of these instructions require us to release on PyPI/conda-forge first, so those have been commented out for now. Once we cut a release we can uncomment these.

Add installation instructions

---

tests/datasets/test_eurosat.py
tests/datasets/test_ucmerced.py
torchgeo/datasets/eurosat.py
torchgeo/datasets/geo.py
torchgeo/datasets/ucmerced.py
torchgeo/datasets/utils.py

- Refactored the `UCMerced` and `EuroSAT` datasets to inherit from `VisionClassificationDataset` and removed boilerplate code
- Update tests to increase code cov
Note that I removed some attributes other than the `class_counts`, however they are still available since they are computed under the hood by `torchvision.datasets.ImageFolder`. Stealing from the docs:
```
Attributes:
classes (list): List of the class names sorted alphabetically.
class_to_idx (dict): Dict with items (class_name, class_index).
imgs (list): List of (image path, class_index) tuples
```

Refactor UCM & EuroSAT to VisionClassificationDatasets

---

benchmark.py
experiments/run_benchmarks_experiments.py
torchgeo/datasets/geo.py

This PR makes the following changes:

Fix various bugs in data loader benchmarking script

---

tests/datasets/test_geo.py
torchgeo/datasets/geo.py

I was debugging the dataset/sampler benchmarking script and thought that it would be useful to have a quick way to gauge the number of files in a `GeoDataset` index. This PR adds a `__len__` method to `GeoDataset` and `ZipDataset` defined as the number of files in the index.
Easy to see how many geospatial files we found on the filesystem. Also matches `VisionDataset` where we implement `__len__`.
As we extensively discuss in our paper, the _length_ of a geospatial dataset is a really ambiguous term. Here we are rather arbitrarily choosing a specific length definition that is different than what people typically use (number of patches) since that could be infinite.
We could print the number of files in the `__str__` method without implementing `__len__` if we think it's too ambiguous to …

Add __len__ method to GeoDataset and ZipDataset

---

README.md
tests/datasets/test_cyclone.py
torchgeo/datasets/cyclone.py
torchgeo/trainers/cyclone.py

This dataset uses a random key name "wind_speed" instead of a more typical name like "target". This makes it harder to combine with other regression datasets using a single trainer.
Once this is merged I'm planning to refactor things to make a single `RegressionTask` trainer that I can use for Cyclone, COWCCounting, and other regression datasets.

TropicalCyclone dataset: use target for sample key

---

torchgeo/datasets/spacenet.py
torchgeo/models/changestar.py
torchgeo/models/fccd.py
torchgeo/trainers/chesapeake.py
torchgeo/trainers/cyclone.py
torchgeo/trainers/landcoverai.py
torchgeo/trainers/naipchesapeake.py
torchgeo/trainers/resisc45.py
torchgeo/trainers/sen12ms.py
torchgeo/trainers/so2sat.py
torchgeo/trainers/tasks.py
torchgeo/trainers/ucmerced.py
torchgeo/trainers/utils.py

I'm sure there are more things I missed, but these were the most obvious things I noticed while looking through our API docs.
Overall I'm pretty disappointed that `pydocstyle` didn't catch any of these automatically. In the long run I think we'll need to contribute a few improvements to `pydocstyle` so that we don't have to manually search for these kinds of things.

Various improvements to API docs

---

tests/data/ucmerced/uc_merced-test.txt
tests/data/ucmerced/uc_merced-train.txt
tests/data/ucmerced/uc_merced-val.txt
tests/datasets/test_ucmerced.py
tests/trainers/test_ucmerced.py
torchgeo/datasets/geo.py
torchgeo/datasets/ucmerced.py
torchgeo/trainers/ucmerced.py

The "In-Domain Representation Learning for Remote Sensing" paper contains train/val/test splits for the datasets that they test with -- https://github.com/google-research/google-research/blob/master/remote_sensing_representations/README.md. In the cases of UC Merced, RESISC45, and EuroSAT (which don't have official train test splits) I think it makes more sense to use these splits instead of just returning the whole dataset. These splits are being "used in the wild" already (e.g. the SeCo paper uses the BigEarthNet split from the In Domain ... paper although the BigEarthNet dataset defines its own (different) splits).

Add train/val/test splits to UCMerced

---

tests/models/test_resnet.py
torchgeo/models/__init__.py
torchgeo/models/resnet.py

Still need to add tests, but this is basically what I'm thinking for pre-trained models. It's almost a carbon-copy of how torchvision does things, but with an added "sensor" field that lets you specify which satellite you want your model trained on.
Some things to consider:
* Do we want to support model + sensor + task combinations? I'm thinking not since torchvision only supports model and not model + task
* Do we want to support arbitrary band subsets? We could support Sentinel 2 "all bands" and "rgb" but I don't think we want to support any more than we have to
* Do we want error checking or some way to let users know which models have been trained for which sensors?

Add pre-trained models for ResNet

---

environment.yml
setup.cfg
tests/trainers/test_tasks.py
tests/trainers/test_utils.py
torchgeo/trainers/tasks.py
torchgeo/trainers/utils.py

Pretty much any new class of models we add to the classification task (or soon-to-be segmentation task) will need to have its first conv layer replaced. This PR refactors that logic and adds VGG as a template for "how to add new types of models to the trainers".

Adding VGG models to the classification task and refactoring

---

docs/conf.py
torchgeo/datasets/geo.py

This should fix the failing unit tests.
For context, Sphinx displays the base class of each class in our documentation. When that base class comes from another library (not TorchGeo), Sphinx attempts to find where it is documented and add a link. It does this by looking at the `intersphinx_mapping` setting.
The reason that this previously worked and all of a sudden broke is that Sphinx just released version 4.3.0 yesterday, which includes a fix for https://github.com/sphinx-doc/sphinx/issues/9607. Previously, the base class wasn't being detected correctly. Now that it is being correctly detected, Sphinx is complaining that it can't find the documentation for it.

VisionClassificationDataset: fix Sphinx base class mapping

---

tests/datasets/test_eurosat.py
tests/datasets/test_landcoverai.py
tests/datasets/test_resisc45.py
tests/datasets/test_seco.py
tests/datasets/test_so2sat.py
tests/datasets/test_ucmerced.py
tests/datasets/test_utils.py
torchgeo/datasets/etci2021.py
torchgeo/datasets/eurosat.py
torchgeo/datasets/landcoverai.py
torchgeo/datasets/resisc45.py
torchgeo/datasets/seco.py
torchgeo/datasets/so2sat.py
torchgeo/datasets/ucmerced.py
torchgeo/datasets/utils.py
torchgeo/datasets/xview.py

Working on adding/fixing plot functions for the datasets that don't have them.
Currently on my list

Add plot functions to datasets

---

tests/datasets/test_spacenet.py
torchgeo/datasets/spacenet.py
torchgeo/datasets/utils.py

Changes:
- Add plot function to SpaceNet base class
- Explicitly check whether raster CRS is equal to vector CRS and transform polygon features accordingly
- ~Add `contrast_stretch` to correctly convert between types~
- Added axis param to `percentile_normalization` and updated utils ` __all__`

Add plot function for SpaceNet datasets

---

tests/transforms/test_transforms.py

In Kornia v0.6.2 release, a fix was made to correctly augment boxes when a random flip augmentation was performed in `kornia.augmentation.AugmentationSequential`. A check was also added to ensure batch dimensions agree.
To accommodate our tests with these updates:
- add batch dim to dummy box data
- correct the expected output of the augmented boxes 
Relevant kornia PR https://github.com/kornia/kornia/pull/1304

Kornia v0.6.2 test updates

---

environment.yml
setup.cfg

Open3d just made a new release 0.14.1 and added support for Python 3.9. This PR updates `setup.cfg` and `environment.yaml`.
- Remove unused `open3d-admin` conda channel
- Removes Python < 3.9 open3d dependency

Updated dependencies for Open3d v0.14.1

---

setup.cfg

From what I can tell in https://github.com/python/mypy/issues/11763, there seems to be a bug in the latest mypy release. Until we can confirm, let's avoid using it for now. If this later turns out to be an issue with our code or with pytest's type hints, this can be reverted later.

Fix bug with latest version of mypy

---

docs/user/installation.rst
environment.yml

Fixes #293 
Tried this on my Linux machine and it installs pytorch 1.10.0 with gpu support.

Replace pytorch-gpu with pytorch in environment.yml

---

tests/transforms/test_indices.py
torchgeo/transforms/__init__.py
torchgeo/transforms/indices.py

Relevant to a lot of fire pre and post fire monitoring: https://www.usgs.gov/landsat-missions/landsat-normalized-burn-ratio

Add normalized burn ratio transform

---

tests/datasets/test_gid15.py
torchgeo/datasets/gid15.py

Added plotting method for GID15 dataset.

plotting method for GID15 dataset

---

.github/workflows/docs.yaml
.github/workflows/release.yaml
.github/workflows/tests.yaml
setup.cfg
tests/datasets/test_advance.py
tests/datasets/test_idtrees.py
tests/datasets/test_nwpu.py
tests/datasets/test_resisc45.py
tests/datasets/test_so2sat.py
tests/datasets/test_utils.py
torchgeo/datasets/idtrees.py
torchgeo/datasets/nwpu.py
torchgeo/datasets/so2sat.py

With this PR, I would like to introduce a new definition of required dependencies: anything that is required to import any part of the library. Any optional dependencies, such as those listed under the `[options.extras_require]` section of `setup.cfg` must be guarded by try-excepts to notify the user that a certain library is missing and is needed for the feature they are trying to use. Many package managers, including Spack and Conda, will try to import sections of the library to ensure that things were installed correctly. These tests shouldn't fail because optional dependencies are missing. To enforce this, I've added a test that doesn't install the optional dataset dependencies to ensure that the tests still pass.
Closes #72 
Related to #230, #249

Rework list of required dependencies

---

tests/datasets/test_cyclone.py
tests/datasets/test_gid15.py
torchgeo/datasets/cyclone.py
torchgeo/datasets/gid15.py

Adding plotting method for Cyclone dataset.

plotting method Cyclone dataset

---

tests/datasets/test_geo.py
torchgeo/datasets/geo.py

This is an ugly hack, but it does allow users to use parallel data loading on macOS/Windows. The `benchmark.py` script now works on macOS with `--num-workers` > 0.
Fixes #184

Fix GeoDataset pickling

---

pyproject.toml
tests/transforms/test_transforms.py

Follow-up to #268
Our tests currently crash if you use Kornia 0.6.1. Also, even if you use a valid version of Kornia, there are warnings printed by the library.

Transform tests: min Kornia version, filter warnings

---

.github/workflows/release.yaml

- Refactors all gdal usage with rasterio
- Removes tqdm usage

Indices Tutorial Refactor

---

docs/conf.py

If you view the tutorials on RtD, we now default to the latest stable release. However, the "Open in Colab" button still opens up the `main` version. This PR fixes that.
The only remaining "gotcha" is that all versions of the tutorial will `pip install torchgeo`, so they'll all use the latest stable release, even if something has changed since then in main. We can avoid this issue by defaulting to the docs for the latest stable release, but as soon as someone tries a different versions of the docs it may not work.
Fixes #274
Fixes #310

Open specific version of tutorial in Colab

---

tests/datasets/test_spacenet.py
torchgeo/datasets/spacenet.py

Add option to plot prediction if present in sample dict
Plot works for the following cases:
- Plot only image
- Plot image and mask(label)
- Plot image, mask and prediction
Following cases won't work:
- Plot only prediction
- Plot only mask
- Plot mask and prediction 
- Plot image and prediction
First two might not be that important. Not sure if we want to support the last two. If required this could be done in a follow up PR.

Update SpaceNet plot fns

---

docs/_static/workaround.css
docs/conf.py

Adds a "Launch in Hub" button similar to our existing "Open in Colab" button that opens a copy of the tutorial on the Planetary Computer. Note that this requires a Planetary Computer account to use.
@TomAugspurger @RitwikGupta 
Closes #117

Add Launch in Hub button to tutorials

---

docs/conf.py
docs/requirements.txt
environment.yml

Because we use mypy in strict mode, all methods must declare a return type. For procedures with no return value, this is None. Sphinx tries to document this by adding "Return type: None" to all procedures, but we don't really need this clutter. This PR removes that.

Docs: get rid of "Return type: None" for procedures with no return value

---

torchgeo/transforms/indices.py
torchgeo/transforms/transforms.py

We could remove `warn_unused_ignores = true` from `pyproject.toml` to prevent these kind of things from breaking CI, but I don't want them to build up too much. Maybe we run `mypy .` on PRs and `mypy --strict .` on releases.

Fix new mypy warnings

---

evaluate.py
pyproject.toml
torchgeo/__init__.py
train.py

This PR moves all imports out of `torchgeo/__init__.py`. Now that #321 has been merged, we no longer need imports in this file to avoid circular import dependencies (#276). The benefits of this are speed. Previously, we were importing all of `torchgeo.datamodules` and `torchgeo.trainers` no matter what component of `torchgeo` we are actually trying to import.
```console
$ time python -c 'from torchgeo.datasets import GeoDataset'
real	0m9.481s
user	0m5.799s
sys	0m1.887s
$ time python -c 'from torchgeo.samplers import GeoSampler'
real	0m9.311s
user	0m5.699s
sys	0m1.856s
$ time python -c 'from torchgeo.models import resnet50'
real	0m8.822s
user	0m5.731s
sys	0m1.854s
```
```console
$ time python -c 'from torchgeo.datasets import GeoDataset'
real	0m3.826s
user	0m2.808s
sys	0m0.985s
$ time …
```

Move imports out of global namespace

---

train.py

Some changes to imports were made in #325 which breaks `train.py`. This PR adds the correct imports to `train.py`.

train.py import fix

---

tests/datasets/test_cv4a_kenya_crop_type.py
torchgeo/datasets/cv4a_kenya_crop_type.py

Proposition for adding a plotting method to this dataset. 
As the image is a timeseries, the plotting method has a time_step variable that lets the user specify which timestep should be shown. I am not sure if that is how you would like to handle this, so open for suggestions.
Example plot
:

Add plotting method for CV4A Kenya Crop Type Dataset

---

tests/datasets/test_sen12ms.py
torchgeo/datasets/sen12ms.py

This PR adds plot method to Sen12ms dataset, replacing #320 because of bad rebase.
Example:

Add plotting method and band selection to Sen12ms, replacing #320

---

docs/conf.py
tests/datasets/test_utils.py
torchgeo/datamodules/utils.py
torchgeo/datasets/advance.py
torchgeo/datasets/bigearthnet.py
torchgeo/datasets/chesapeake.py
torchgeo/datasets/cowc.py
torchgeo/datasets/cv4a_kenya_crop_type.py
torchgeo/datasets/cyclone.py
torchgeo/datasets/etci2021.py
torchgeo/datasets/fair1m.py
torchgeo/datasets/geo.py
torchgeo/datasets/gid15.py
torchgeo/datasets/idtrees.py
torchgeo/datasets/landcoverai.py
torchgeo/datasets/levircd.py
torchgeo/datasets/loveda.py
torchgeo/datasets/nasa_marine_debris.py
torchgeo/datasets/nwpu.py
torchgeo/datasets/oscd.py
torchgeo/datasets/potsdam.py
torchgeo/datasets/spacenet.py
torchgeo/datasets/utils.py
torchgeo/datasets/vaihingen.py
torchgeo/datasets/xview.py

I don't have most of these data files lying around so I can't actually test the type of these arrays, so I guessed int for most of them. I wonder if there's a way to do dynamic type analysis where you compare the actual types with what mypy expects them to be.
Note that type hints are in quotes until we either 1) drop Python 3.6 support, or 2) drop numpy 1.20 support, or both.

Add type hints for numpy

---

.pre-commit-config.yaml

numpy 1.22.0 added type annotations for `np.percentile`, `np.load` and `np.concatenate` (among others) so it needs to be added as an additional dependency.

Add numpy dependency to pre-commit config

---

tests/transforms/test_indices.py
tests/transforms/test_transforms.py
torchgeo/transforms/__init__.py
torchgeo/transforms/indices.py

All the indices currently included are just ratios of sums. The helper functions also depend on the user knowing what the index of the relevant bands are to begin with.
Since this knowledge of the underlying index is already required, it's cleaner to have one generalized module for difference indices.

Refactor all indices to one module.

---

environment.yml
setup.cfg

`PadTo` was added in kornia 0.5.11 (kornia/kornia#1286). This PR updates the min version accordingly. Currently `K.PadTo` is only used in the OSCDDatamodule ([here](https://github.com/microsoft/torchgeo/blob/8ab254a24c2778ddaa64c163c99bfac49987bbf4/torchgeo/datamodules/oscd.py#L110)).

Update min kornia version to support PadTo

---

.github/workflows/tests.yaml
setup.cfg

If this doesn't work I'll try moving the constraint to `.github/workflows/tests.yaml`.

Fix PyTorch + setuptools bug

---

environment.yml
evaluate.py
setup.cfg
torchgeo/trainers/classification.py
torchgeo/trainers/segmentation.py

torchmetrics renamed IoU to JaccardIndex: https://github.com/PyTorchLightning/metrics/pull/662
IoU isn't removed yet, just deprecated, but it will be removed in 0.8, so I think it's better to require the latest version now and future-proof our code for later.

torchmetrics: IoU -> JaccardIndex

---

setup.cfg
tests/datasets/test_geo.py
torchgeo/datasets/geo.py

When trying to compute the length of an empty GeoDataset, instead of returning 0, rtree crashes. See https://github.com/Toblerity/rtree/issues/204 for a description of the issue. We can instead use `Index.get_size()` which has a try-except that happens to catch this issue and return 0.
`Index.get_size()` is undocumented and was added in rtree 0.9.4, which is relatively new. We could instead add our own try-except with the same implementation as `Index.get_size()` if we want to support older versions of rtree. Thoughts on this?

Fix len for empty GeoDataset

---

tests/samplers/test_batch.py
tests/samplers/test_single.py
torchgeo/samplers/batch.py
torchgeo/samplers/single.py

Fixes #319 
@RitwikGupta @tritolol

Samplers: avoid bounding boxes smaller than patch size

---

torchgeo/datasets/idtrees.py

The included citation was for an older version of the competition that does
not match the dataset. This updates it to the correct DOI for the data.

Use proper citation for IDTReeS dataset

---

tests/datasets/test_utils.py
torchgeo/datasets/utils.py

This PR adds area/volume attributes to the `BoundingBox` class. 
This is needed for a check I would like to add for #319, but I figured I would submit it as a separate PR to keep things easier to review.

BoundingBox: add area/volume attributes

---

tests/transforms/test_indices.py
torchgeo/transforms/__init__.py
torchgeo/transforms/indices.py

This PR adds the following new spectral indices:

Add BNDVI/NDRE spectral indices

---

tests/datasets/test_landcoverai.py
torchgeo/datasets/landcoverai.py

See #99 for rationale/design.
This dataset actually has 3 phases: download, extract, and generate patches from larger images. We could actually have a third `_generate` phase of `_verify` in case we want to allow people to delete the original image tiles after the patches are generated. Not sure if that's necessary though.

LandCover.ai: support already-downloaded dataset

---

tests/datasets/test_so2sat.py
torchgeo/datasets/so2sat.py

This PR addresses the last comment by Adam in issue #289 about adding band selection to the So2Sat Dataset. Changes I made:
- add band selection as a sequence and select desired bands in __getitem__
- adopt the plot method to look for RGB indices and only plot then
- since the dataset takes a specific split as an argument, I thought it would make sense that the integrity check also only checks the specific selected split, so that not all splits need to have been downloaded
The remaining question I have is whether there is a standard naming convention for the S1 bands, described [in the dataset repo](https://github.com/zhu-xlab/So2Sat-LCZ42). I couldn't find one and therefore just prepended "S1".
Plot examples:

Add band selection to So2Sat Dataset and adopt plot method

---

docs/conf.py
torchgeo/transforms/indices.py

See #387 
We may need to develop a consistent naming scheme for bands. For example, some indices take in the index of the red-edge band, but many satellites don't have a red-edge band, so we use red instead. The parameter names should be somehow consistent in this scenario.
I haven't yet added common use cases and interpretation to the docs. That can probably be done in a separate PR.

Add formulas to indices docs

---

torchgeo/datasets/chesapeake.py

@calebrob6 can you see if this fixes #419?

Chesapeake: allow multiple datasets to share same root

---

torchgeo/datasets/cdl.py

CDL is an annual agricultural product, usually released the following winter/spring after the growing season ends.

CDL: add MD5 for 2021 data

---

tests/datasets/test_chesapeake.py
torchgeo/datasets/chesapeake.py
torchgeo/datasets/geo.py

This PR adds a plot method to the Chesapeake dataset baseclass to address #253. I was unable to run pytest, because the currently generated fake data cannot be unzipped:
`NotImplementedError: That compression method is not supported`
should I change the archive method in the base data.py class to the `shutil.make_archive()` used in other data.py files?

Add plot method to base chesapeake

---

torchgeo/datasets/geo.py

Make RasterDataset not override custom cmaps

---

torchgeo/datasets/cdl.py

Previously, CDL was distributed as Erdas Imagine .img files. It looks like it is now distributed as GeoTIFF .tif files. This means that all of the checksums have now changed.

CDL: update checksums

---

torchgeo/datasets/benin_cashews.py
torchgeo/datasets/chesapeake.py

exposing geoinformation in the return dict of __getitem__ for benin_cashews.py

BeninSmallHolderCashews: return geospatial metadata in sample

---

tests/transforms/test_indices.py
torchgeo/transforms/__init__.py
torchgeo/transforms/indices.py

Added Class for supporting three band differential normalized indices e.g.[Green-Blue NDVI]

3band indices

---

torchgeo/datasets/cdl.py

Fixes #423 
Maybe someone with a wired internet connection can double check that every year of data has a `.tif` file? From what I call, this dataset was not consistent across all years. I feel like some years might have used `.img`...
Unfortunately this prevents users from changing the file format of the data they download. But those users can always override `filename_glob` if they need to.

CDL: don't pick up .tif.ovr files

---

tests/datasets/test_cms_mangrove_canopy.py
torchgeo/datasets/cms_mangrove_canopy.py

When adding the CMSMangroveCanopy dataset in #391, I did not add its own plot method. This PR does so.
Example:

Add own plot method to CMSMangroveCanopy 

---

tests/datasets/test_astergdem.py
tests/datasets/test_cdl.py
tests/datasets/test_chesapeake.py
tests/datasets/test_cms_mangrove_canopy.py
tests/datasets/test_esri2020.py
tests/datasets/test_eudem.py
tests/datasets/test_gid15.py
tests/datasets/test_globbiomass.py
tests/datasets/test_sentinel.py

This PR closes #436 by adding `plt.close()` to test files in order to prevent file handle leaks.

Missing plt.close() on dataset tests

---

torchgeo/datamodules/resisc45.py

The statistics I calculated over the RESISC45 training set do not match what we have in the DataModule -- the stdevs are particularly wrong:

RESISC45 statistics fix

---

tests/samplers/test_batch.py
tests/samplers/test_single.py

Turns out the tests were failing not because we weren't pickling properly but because the index was empty.
Closes #349

Fix integration tests on macOS/Windows

---

.gitattributes

This allows `git diff` to show changes to text files in `tests/data`. 
Previously, we treated all test files as `binary` (equivalent to `-text -diff`). This resulted in useless diffs like:
```console
$ git diff
diff --git a/tests/data/cowc_counting/data.py b/tests/data/cowc_counting/data.py
index b612f92..c5ef84a 100755
Binary files a/tests/data/cowc_counting/data.py and b/tests/data/cowc_counting/data.py differ
```
However, `-text` is sufficient to prevent line endings from being changed (necessary for stable cross-platform checksums). Now, all text files diff properly. I also added back line ending changes to `data.py` since we never need to checksum that.

gitattributes: allow diff of test data

---

tests/test_train.py

Discovered during 0.2.1 release prep. Already backported to the releases/v0.2 branch.
Looks like an update to pytorch-lightning or to our `train.py` means that these tests were out-of-date.

Update train.py integration tests

---

tests/datasets/test_chesapeake.py

Discovered this during the 0.2.1 release prep. Already backported to the releases/v0.2 branch.
The `test_already_downloaded` test was failing when `zipfile_deflate64` isn't installed because this test doesn't use the fixture.

Chesapeake: skip all tests if zipfile_deflate64 missing

---

.github/workflows/tests.yaml

Reverts microsoft/torchgeo#357
New PyTorch version has been released so this workaround is no longer needed.

Revert "Fix PyTorch + setuptools bug"

---

setup.cfg

Previously we had to specify the exact version to use in order to work around a bug with pip and pre-release versions. Black is no longer pre-release so this hack should no longer be needed.

setup.cfg: no longer need hack for pre-release black

---

.github/workflows/tests.yaml

h5py now provides Windows wheels, so we shouldn't have to install it with conda anymore.

CI: h5py now provides Windows wheels

---

.github/workflows/tests.yaml
environment.yml
pyproject.toml
setup.cfg

Python 3.6 is no longer supported by the [Python Software Foundation](https://endoflife.date/python), nor is it supported by [PyTorch](https://github.com/pytorch/pytorch/blob/v1.11.0/setup.py#L209). This PR drops Python 3.6 support. All users should upgrade to a modern version of Python in order to use future TorchGeo releases.
The biggest new language feature in Python 3.6 is the ability to use:
```python
from __future__ import annotations
```
This allows us to use annotation capabilities from Python 3.10 in Python 3.7–3.9 by avoiding annotation evaluation at run-time. I'll add this in a separate PR since it's a more controversial change.
Reboot of #326
Closes #413
@weiji14

Drop Python 3.6 support

---

tests/trainers/test_classification.py
tests/trainers/test_regression.py
tests/trainers/test_segmentation.py
torchgeo/trainers/classification.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py

PyTorch Lightning 1.6.0 was released today and includes better type hints, causing our mypy tests to fail. This PR updates some things related to PL 1.6.
The reason that these type ignores are needed (and the try-except is needed) is that all model/datamodule/trainer attributes are optional. We could instead replace the try-except with a `hasattr(...)` for literally every attribute, but that gets cumbersome pretty quickly. I may do this in the future, but for now, the try-except protects us.

Fix PyTorch Lightning 1.6 type hints

---

.github/workflows/style.yaml
.pre-commit-config.yaml
docs/user/contributing.rst
setup.cfg
tests/data/globbiomass/data.py
tests/data/openbuildings/data.py
tests/datasets/test_openbuildings.py
tests/test_train.py
torchgeo/datasets/advance.py
torchgeo/datasets/agb_live_woody_density.py
torchgeo/datasets/benin_cashews.py
torchgeo/datasets/bigearthnet.py
torchgeo/datasets/cms_mangrove_canopy.py
torchgeo/datasets/eurosat.py
torchgeo/datasets/globbiomass.py
torchgeo/datasets/idtrees.py
torchgeo/datasets/levircd.py
torchgeo/datasets/nasa_marine_debris.py
torchgeo/datasets/openbuildings.py
torchgeo/datasets/oscd.py
torchgeo/datasets/resisc45.py
torchgeo/datasets/sen12ms.py
torchgeo/datasets/ucmerced.py
torchgeo/datasets/usavars.py
torchgeo/datasets/utils.py
torchgeo/models/fcsiam.py

`pyupgrade` is a tool similar to `black` and `isort` that auto-formats code to use language features introduced in newer versions of Python. This PR runs `pyupgrade` on the code base and adds a CI test to ensure that all code uses modern language features.
I'm actually hesitant to add this to CI. The developer of `pyupgrade` is the same person who develops git pre-commit hooks. This developer has a history of rude comments and dismissive remarks towards users who open issues or suggest new features. For example, `pyupgrade` doesn't work unless you manually specify a list of all files you want to upgrade (hence `$(find . -name "*.py")`) because the developer couldn't understand why anyone would possibly want to use this tool outside of a commit hook …

Upgrade all files to Python 3.7+ syntax

---

tests/models/test_fcsiam.py

This PR fixes the requirement for FCSiam model tests to have internet access. Tested with wifi and ethernet disabled.
Closes #495

Default FCSiam models to random init for tests

---

docs/api/samplers.rst
tests/samplers/test_single.py
torchgeo/samplers/__init__.py
torchgeo/samplers/single.py

Many existing `VisionDatasets` actually contain geospatial metadata. These datasets should be converted to `GeoDatasets` (#83). However, `GeoDatasets` are a bit more complicated than `VisionDatasets` and require a `GeoSampler` to use. This PR adds a `PreChippedGeoSampler` to make this transition easier.
For `VisionDatasets`, sampling is quite simple:
```python
train_dataset = ...
train_dataloader = DataLoader(train_dataset, shuffle=True)
test_dataset = ...
test_dataloader = DataLoader(test_dataset)
```
However, it was much trickier to get the same behavior for `GeoDatasets`. Previously, a user would need to do something like:
```python
SIZE = 256  # size of each image
train_dataset = ...
train_sampler = RandomGeoSampler(train_dataset, size=SIZE, length=len(train_dataset))
train_dataloader …
```

Add PreChippedGeoSampler for pre-chipped geospatial datasets

---

.pre-commit-config.yaml

I'm assuming this list is ordered. `pyupgrade` can cause formatting changes that require `black` to be re-run, so it should be run first.
@ashnair1

git pre-commit: run pyupgrade first

---

torchgeo/datasets/sen12ms.py

Fixes #500, not 100% sure yet whether this fix is the one we want. Feedback much appreciated!

Fix data casting for the SEN12MS dataset

---

torchgeo/trainers/byol.py

To avoid shape errors, we pass the `in_channels` argument from `BYOLTask` to `BYOL`.

Fix error when using other than 4 channel images with BYOL task

---

environment.yml

add channels to prevent conda's ResolvePackageError on Windows

---

setup.cfg
torchgeo/trainers/segmentation.py

Hoping this fixes the failing CI. See https://github.com/microsoft/torchgeo/runs/6733678644?check_suite_focus=true for an example of the error message.
See https://github.com/PyTorchLightning/metrics/pull/1036 for the change that I believe caused the tests to fail. I'm not sure if this setting is right for us, or if there's something else that needs to be done, but this should at least fix CI.

Fix compatibility with torchmetrics 0.9, failing Windows tests

---

setup.cfg

Apparently `setup_requires` is deprecated in favor of `pyproject.toml`. Also, setuptools is working on adding `pyproject.toml` support. 
https://setuptools.pypa.io/en/latest/userguide/dependency_management.html

setuptools: setup_requires is deprecated

---

pyproject.toml
requirements.txt
setup.cfg

Another attempt to make TorchGeo more stable. Assuming that our dependencies follow [semver](https://semver.org/), this PR assures that each TorchGeo release will continue to build for the indefinite future. 
For a concrete example of why this PR is necessary, our 0.2.1 release currently doesn't work with the latest version of torchmetrics since 0.9 introduced a backwards-incompatible change (fixed in #555). Our 0.2.0 and older releases also doesn't work with torchmetrics 0.8 due to another backwards-incompatible change (fixed in #361, #382). Since neither release specified an upper bound on the torchmetrics dependency, the simple `pip install torchgeo` no longer works, you have to manually specify a compatible version of torchmetrics too. In Spack and Conda, we can specify this …

Add upper bounds to dep versions

---

.github/dependabot.yml
environment.yml
requirements.txt
setup.cfg

Tests were failing due to the recent release of protobuf 4.21.0. See protocolbuffers/protobuf#10051
Error propagation: protobuf > tensorboard > pytorch_lightning > torchgeo

Pin protobuf<4

---

tests/trainers/conftest.py
torchgeo/trainers/utils.py

When loading a model trained with BYOLTask using the "weights" parameter in ClassificationTask, the following error occurs:
```
Traceback (most recent call last):                                  
File "finetune_ssl_on_eurosat.py", line 14, in <module>                     
task = ClassificationTask(classification_model="resnet50", loss="ce",
File "/torchgeo/torchgeo/trainers/classification.py", line 103, in __init__
self.config_task()
File "/torchgeo/torchgeo/trainers/classification.py", line 77, in config_task
self.config_model()
File "/torchgeo/torchgeo/trainers/classification.py", line 66, in config_model
name, state_dict = utils.extract_encoder(self.hyperparams["weights"])
File "/torchgeo/torchgeo/trainers/utils.py", line 55, in extract_encoder                       
raise ValueError( …
```

Fix loading encoder weights trained with BYOL

---

torchgeo/datasets/bigearthnet.py

Md5 value for file BigEarthNet-S1-v1.0.tar.gz seems like incorrect which causes code to download the whole data from scratch even though it exists.
```
$ cat BigEarthNet-S1-v1.0.tar.gz.md5sum 
94ced73440dea8c7b9645ee738c5a172  BigEarthNet-S1-v1.0.tar.gz
$ cat BigEarthNet-S2-v1.0.tar.gz.md5sum 
5a64e9ce38deb036a435a7b59494924c  BigEarthNet-S2-v1.0.tar.gz
```

Update md5sum of the s1 data file

---

environment.yml
pyproject.toml
setup.cfg
tests/trainers/test_byol.py
tests/trainers/test_classification.py
tests/trainers/test_regression.py
tests/trainers/test_segmentation.py
torchgeo/datamodules/landcoverai.py
torchgeo/datamodules/resisc45.py
torchgeo/datasets/cyclone.py
torchgeo/datasets/geo.py
torchgeo/datasets/seco.py

This is the third PR in a series of attempts to improve the stability and robustness of TorchGeo's build system (#557, #551).
If you look at the logs for our unit tests, you'll see a slew of warning messages, desperately trying to warn us that TorchGeo is using deprecated features that will be removed in future versions of our dependencies. Up until now, these were ignored until someone noticed/reported an issue. With this PR, these kind of warnings will become fatal. We weren't able to do something this extreme before, but now that we use dependabot, we can restrict these kind of failures to version update PRs, not user PRs.
* When a dependency changes its API, should we use the new API and bump the required version of that dependency, or should we maintain compatibility with historic …

Resolve DeprecationWarnings

---

torchgeo/datasets/bigearthnet.py
torchgeo/datasets/cyclone.py
torchgeo/datasets/eddmaps.py
torchgeo/datasets/eurosat.py

We should always use HTTPS when available. UC Merced doesn't support HTTPS unfortunately.

Datasets: download from HTTPS

---

torchgeo/datasets/landcoverai.py

Closes #559
I double checked that the checksum of the zip file is the same when downloaded from this new link.

Update landcover.ai dataset download link

---

environment.yml

With conda-forge/pycocotools-feedstock#20, [pycocotools](https://anaconda.org/conda-forge/pycocotools) from conda-forge now officially supports windows.

Remove esri channel

---

docs/user/installation.rst

Added a note clarifying installation procedure for Windows users.
As @adamjstewart  mentioned in #561, due to conda-forge feedstocks not allowing channels outside of `conda-forge and defaults`  (as mentioned [here](https://github.com/conda-forge/deepforest-feedstock/pull/26#discussion_r786278832)) and [conda-forge/pytorch](https://anaconda.org/conda-forge/pytorch) not supporting Windows, users will not be able to install `conda install -c conda-forge torchgeo` directly.

Add note about Windows installation

---

docs/api/datamodules.rst
docs/api/datasets.rst
docs/api/models.rst

Closes #569
Cluttered, can't easily count the number of datasets:
Simple, easy to find the dataset you're looking for:

Docs: shorter dataset/datamodule/model names

---

.github/workflows/release.yaml
.github/workflows/tests.yaml
environment.yml
pyproject.toml
requirements/requirements-min.txt
requirements/requirements.txt
setup.cfg
tests/datasets/test_advance.py
tests/datasets/test_idtrees.py
tests/datasets/test_openbuildings.py
tests/datasets/test_so2sat.py
tests/datasets/test_usavars.py
tests/datasets/test_zuericrop.py
tests/trainers/test_classification.py
tests/transforms/test_transforms.py
torchgeo/datasets/advance.py
torchgeo/datasets/cyclone.py
torchgeo/datasets/seco.py

This is the fourth PR in a series of attempts to improve the stability and robustness of TorchGeo's CI (#567, #557, #551).
With this PR, we now have a minimum supported version listed for all of our dependencies, and we actively test to ensure that this stays up-to-date with each commit. 
In the past, I tried not to overly restrict our dependencies if I didn't know the oldest supported version. With this PR, I'm taking the policy of "the oldest supported version is the oldest we can test". For example, many of our dependencies are pinned to versions due to Python 3.7 support or because another dependency requires a newer version, even if an older version would work with our code.
Closes #32

Test minimum version of deps

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/documentation.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/labeler.yml

This PR adds issue templates to the repository. They are loosely based on [PyTorch's](https://github.com/pytorch/pytorch/issues/new/choose) and [Spack's](https://github.com/spack/spack/issues/new/choose) issue templates. See the [official docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests) for more details on possible values and syntax.
I don't really know how to view/test these without forking the repo and merging them to main in the fork? I guess we can do all the wordsmithing in this PR and fix any bugs we find after merging.
Closes #584

Add issue templates

---

.github/workflows/style.yaml
.gitignore
pyproject.toml
setup.cfg

In order to build the docs locally, pytorch-sphinx-theme _must_ be installed in editable mode in `docs/src`: https://github.com/pytorch/pytorch_sphinx_theme/issues/143
This PR tells git and our linters to ignore this installation.

Ignore pytorch-sphinx-theme installation

---

conf/chesapeake_cvpr.yaml
conf/etci2021.yaml
conf/inria.yaml
conf/landcoverai.yaml
conf/naipchesapeake.yaml
conf/oscd.yaml
conf/sen12ms.yaml
tests/conf/chesapeake_cvpr_5.yaml
tests/conf/chesapeake_cvpr_7.yaml
tests/conf/chesapeake_cvpr_prior.yaml
tests/conf/etci2021.yaml
tests/conf/inria.yaml
tests/conf/landcoverai.yaml
tests/conf/naipchesapeake.yaml
tests/conf/oscd_all.yaml
tests/conf/oscd_rgb.yaml
tests/conf/sen12ms_all.yaml
tests/conf/sen12ms_s1.yaml
tests/conf/sen12ms_s2_all.yaml
tests/conf/sen12ms_s2_reduced.yaml
tests/trainers/test_segmentation.py
torchgeo/trainers/segmentation.py

SemanticSegmentationTrainer: ignore_zeros -> ignore_index

---

.github/workflows/tests.yaml
requirements/README.md
requirements/datasets.old
requirements/docs.txt
requirements/min.old
requirements/required.old
requirements/style.txt
requirements/tests.txt
torchgeo/datasets/openbuildings.py

Rasterio and fiona both have Windows wheels now. The only time we need to use conda in CI is to install rasterio on Windows for Python 3.7 which is no longer supported. Once we drop Python 3.7 support (about 12 months from now) conda will no longer be needed in CI.
This PR also stores all dependencies that require a different version for Python 3.7 in separate files. This prevents dependabot from updating them and reporting security vulnerabilities. These files will need to be updated once the numpy ecosystem drops Python 3.8 support.

Store Python 3.7 deps in separate files, use rasterio/fiona Windows wheels

---

docs/api/datasets.rst
docs/api/geo_datasets.csv
docs/api/non_geo_datasets.csv

Various improvements to dataset tables in the docs. Will comment in-line.

Improvements to dataset tables

---

conf/etci2021.yaml
tests/conf/etci2021.yaml
torchgeo/datamodules/chesapeake.py
torchgeo/datamodules/cowc.py
torchgeo/datamodules/cyclone.py
torchgeo/datamodules/etci2021.py
torchgeo/datamodules/eurosat.py
torchgeo/datamodules/fair1m.py
torchgeo/datamodules/inria.py
torchgeo/datamodules/landcoverai.py
torchgeo/datamodules/loveda.py
torchgeo/datamodules/naip.py
torchgeo/datamodules/nasa_marine_debris.py
torchgeo/datamodules/oscd.py
torchgeo/datamodules/resisc45.py
torchgeo/datamodules/sen12ms.py
torchgeo/datamodules/so2sat.py
torchgeo/datamodules/ucmerced.py
torchgeo/datamodules/usavars.py

Cleaning up how preprocessing in the datamodules works in preparation for writing a prediction utility. 
Now, each DataModule has a `preprocess(self, sample)` method that performs the image preprocessing and doesn't break if there isn't a "mask" or "label" key in the sample. This is important as `predict.py` needs to be able to apply the same image pre-processing that a trained model checkpoint used while training, however the new data that the model is being run over will definitely not have any "mask" or "label" parts.
I also took this opportunity to clean up a few things throughout the DataModules -- I'll go through and explain these changes inline with comments.

Datamodule cleanup

---

docs/api/geo_datasets.csv
tests/datasets/test_landsat.py
torchgeo/datasets/cdl.py
torchgeo/datasets/chesapeake.py
torchgeo/datasets/landsat.py
torchgeo/datasets/naip.py
torchgeo/datasets/sentinel.py

We removed the `RasterDataset.plot` method in #476. Landsat was the only remaining `RasterDataset` that didn't have a replacement `plot` method. Added it so we don't have to explain why Landsat used to have a `plot` method but no longer does.
Also cleaned up some typing and documentation mistakes. `RasterDataset.__getitem__` returns `Dict[str, Any]`, not `Dict[str, Tensor]`. Plot methods weren't _added_ in 0.3 since they existed (albeit in the base class) in 0.2. They were _changed_ because they now have completely different inputs.
Example image from Novaya Zemlya, Russia:

Landsat: add plot method

---

.github/workflows/release.yaml
docs/tutorials/trainers.ipynb
pyproject.toml
requirements/tests.txt
setup.cfg
tests/datamodules/test_usavars.py
tests/datasets/test_landcoverai.py
tests/datasets/test_openbuildings.py
tests/datasets/test_reforestree.py
tests/test_train.py
torchgeo/__init__.py
torchgeo/datasets/eurosat.py
torchgeo/datasets/so2sat.py
torchgeo/trainers/segmentation.py
torchgeo/transforms/indices.py

This release contains a number of new features, and brings increased stability to installations and testing. 
In previous releases, not all dependencies had a minimum supported version listed, causing issues if users had old versions lying around. Old releases would also install the latest version of all dependencies even if they had never been tested before. TorchGeo now lists a minimum and maximum supported version for all dependencies. Moreover, we now test the minimum supported versions of all dependencies. Dependencies are automatically updated using dependabot to prevent unrelated CI failures from sneaking into PRs. We hope this makes it even easier to contribute to TorchGeo, and ensures that old releases will continue to work even if our dependencies make backwards-incompatible …

0.3.0 release

---

tests/datasets/test_geo.py
torchgeo/datasets/geo.py

I've had to adjust the test to also account for the extra pixel generated, which seems right to me (`1.9-1.1 = 0.8` which would be 8 pixels with a `res=0.1`).
Fixes #674

Fixes VectorDataset rounding bug causing sample mask size mismatch

---

torchgeo/datasets/idtrees.py

Image used: **OSBS_27**
Before:
After:

Fix coordinate swap bug in IDTReeS

---

docs/tutorials/indices.ipynb
torchgeo/transforms/indices.py

Fixes #713 
We were calculating NDVI incorrectly, using (Red - NIR) instead of (NIR - Red). The only reason our plots looked correct is that we were inverting the color scales.
We used the incorrect band names for SWI. This PR fixes those as well.
I double checked all other indices and things look correct, but I would appreciate it if someone else could triple check.
I'll see if I can get our [blog](https://pytorch.org/blog/geospatial-deep-learning-with-torchgeo/) fixed as well.
@cagsen @isaaccorley @MATRIX4284

Fix NDVI and SWI calculation

---

.github/workflows/tests.yaml

Many of our dependencies, including rasterio, do not provide Windows wheels for Python 3.7. To get around this, we were using Conda to install them. However, this seems to interfere with #701, and increases test setup time. I don't think there's a significant benefit to testing Python 3.7 on Windows since we test 3.7 on other platforms and other versions on Windows. Python 3.7 will still be supported on Windows, it just won't be tested.
Alternative is to keep using Conda and skip rarfile tests, or to drop Python 3.7 support entirely: #656

Skip Python 3.7 Windows tests

---

.github/dependabot.yml

Setuptools has a new release almost daily:
* https://github.com/pypa/setuptools/releases
* https://pypi.org/project/setuptools/#history
We don't need to test every single patch release, let's focus on testing major and minor version updates only.

dependabot: fewer setuptools updates

---

pyproject.toml

Starting with #719, we now test setuptools 65 and it seems to work fine.

setuptools 65 is now tested

---

docs/tutorials/trainers.ipynb

Separated this into a separate PR.

Tutorials: trainers require optional datasets

---

tests/trainers/conftest.py
torchgeo/models/farseg.py
torchgeo/trainers/byol.py
torchgeo/trainers/regression.py

Multi-Weights API was introduced in `0.13`. This PR adjusts the constraint accordingly.

Fix torchvision constraint

---

torchgeo/datasets/idtrees.py
torchgeo/datasets/utils.py

This PR
- clips the bounding box coordinates to the image size (essentially clips boxes that go outside of the image bounds) and filters any boxes that have zero area after clipping.
- fixed bug where id of some geometries were being overriden resulting in some images have no objects.
Fixes part of #684
For `MLBS_5` the boxes before
```python
tensor([[107, -57, 165, -10],
[157, -48, 190, -10],
[127,  24, 198,  92],
[149, 122, 199, 174],
[ 30,  70,  70, 109],
[ -6, -80,  48, -10],
[ 47, 121, 114, 197],
[119,  84, 144, 129],
[108,  74, 129, 101],
[ 36,  21,  83,  73],
[137,  73, 187, 128],
[ 38, -63,  81, -10],
[ 19,  93,  62, 152],
[ 71,  81, 117, 133]])
```
and after filtering
```python
tensor([[127,  24, 198,  92],
[149, 122, 199, 174],
[ 30,  70,  70, 109],
[ 47, 121, 114, 197],
[119, …
```

IDTReeS - Clip boxes outside of image bounds

---

docs/tutorials/benchmarking.ipynb
docs/tutorials/custom_raster_dataset.ipynb
docs/tutorials/getting_started.ipynb
docs/tutorials/indices.ipynb
docs/tutorials/trainers.ipynb
docs/tutorials/transforms.ipynb

This PR fixes a few things to make our tutorials more consistent:
The last one should convert cells that look like:
```
[
]:
```
to the much more visually appealing:
```
[1]:
```

Tutorials: clean up file names, execution codes, and output

---

torchgeo/datasets/inaturalist.py

Link in https://torchgeo.readthedocs.io/en/stable/api/datasets.html#geospatial-datasets table was pointing to https://www.inaturalist.org/ instead of https://torchgeo.readthedocs.io/en/stable/api/datasets.html#inaturalist

iNaturalist: fix ref in datasets table

---

tests/datasets/test_geo.py
torchgeo/datasets/agb_live_woody_density.py
torchgeo/datasets/astergdem.py
torchgeo/datasets/cdl.py
torchgeo/datasets/chesapeake.py
torchgeo/datasets/cms_mangrove_canopy.py
torchgeo/datasets/esri2020.py
torchgeo/datasets/eudem.py
torchgeo/datasets/geo.py
torchgeo/datasets/globbiomass.py
torchgeo/datasets/landsat.py
torchgeo/datasets/sentinel.py

`RasterDataset` by default loads all bands. This PR allows us to be more selective.

Allow band indexing in RasterDataset

---

torchgeo/datasets/xview.py

The `labels` folder exists for the `tier3` imagery that was released after the `tier1` imagery for xView2. It should really be called `targets` but we messed up. When you're merging `tier1` with `tier3`, simply copy all the files from `tier3/labels` to `tier1/targets`.

Remove "labels" folder from verify for xView2

---

tests/datasets/test_geo.py
torchgeo/datasets/geo.py

TL;DR: `UnionDataset` doesn't work and has never worked.
In `UnionDataset.__getitem__`, we were using the following check:
```python
if ds.index.intersection(tuple(query)):
samples.append(ds[query])
```
The idea was that we shouldn't be trying to query from a dataset unless the dataset contains files that overlap with the query. 
However, this doesn't work. `rtree.index.Index.intersection` returns a generator, which always evaluates to True. This resulted in bugs like #769.
The fix is simple: just convert the generator to a list. The list will evaluate to False if it's empty, and the dataset won't be sampled from because it has no overlap.
Our existing tests were basically useless. Our `CustomGeoDatset.__getitem__` just returned the query, so even if the query didn't overlap at all with …

UnionDataset: fix __getitem__ bug

---

tests/trainers/test_classification.py
torchgeo/trainers/classification.py

This PR is similar to #790 and adds a `predict_step` method to `MultiLabelClassificationTask` so that users can utilize PyTorch Lightning's `trainer.predict()` function which will automatically loop and predict over a PyTorch DataLoader e.g.:
```python

MultiLabelClassificationTask predict step

---

docs/api/samplers.rst
tests/samplers/test_single.py
tests/samplers/test_utils.py
torchgeo/samplers/__init__.py
torchgeo/samplers/batch.py
torchgeo/samplers/single.py
torchgeo/samplers/utils.py

Closes #380 @tritolol 
Uses the same logic we use to compute `GridGeoSampler` length, updated by @remtav in #630
Has to wait until the 0.4.0 release since we add a new public function. We could make it private, but I wanted to render the math in the docs 😃

Random GeoSamplers: add default length

---

tests/datasets/test_spacenet.py
torchgeo/datasets/geo.py
torchgeo/datasets/inria.py
torchgeo/datasets/spacenet.py

Apparently not all of our datasets have a default `root` argument.

Datasets: add default 'root' argument

---

tests/trainers/test_classification.py
torchgeo/trainers/classification.py

Running `trainer.predict()` with the `ClassificationTask` fails because the default pytorch_lightning `predict_step` expects a batch tuple and not a dict. This PR overrides `predict_step` to work with our classification datasets.
E.g.
```python
```

ClassificationTask predict step

---

.github/dependabot.yml
.github/workflows/labeler.yml
.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml

We've been seeing a lot of codecov issues. Apparently the bash uploader is deprecated and there's a new version that works completely differently. Hoping this fixes our issues.
Also updated other actions. We could drop the version requirement, but this helps with stability. If only dependabot could handle these files for us too.

Dependabot: manage GitHub Actions

---

conf/nasa_marine_debris.yaml
evaluate.py
tests/conf/nasa_marine_debris.yaml
tests/trainers/test_detection.py
torchgeo/datamodules/nasa_marine_debris.py
torchgeo/datasets/nasa_marine_debris.py
torchgeo/trainers/__init__.py
torchgeo/trainers/detection.py
train.py

Adds a new `ObjectDetectionTask` which uses torchvision's `Faster-RCNN` under the hood.
Closes #442

Add support for ObjectDetection

---

tests/trainers/test_regression.py
torchgeo/trainers/regression.py

Related to #813. This PR adds a `predict_step` method to `RegressionTask` so that users can utilize PyTorch Lightning's `trainer.predict()` function which will automatically loop and predict over a PyTorch DataLoader e.g.:
```python

add predict_step to RegressionTask and tests

---

tests/trainers/test_byol.py
torchgeo/trainers/byol.py

Related to #813. This PR adds a `predict_step` method to `BYOLTask` so that users can utilize PyTorch Lightning's `trainer.predict()` function which will automatically loop and predict over a PyTorch DataLoader e.g.:
```python
```
Note the way the EncoderWrapper is setup is that calling `self(x)` on a batch of images will return the projector output embeddings. However, we only need this during training. For linear evaluation or other downstream tasks we want the output of the image encoder (the output of the avg pool layer of the ResNet). To work around this I had to add another hook to store the embeddings on a forward pass in the `self._embeddings` …

add predict_step to BYOLTask

---

.github/labeler.yml

If a PR modifies one of the root `*.py` scripts, we should add a label that notes this.

Labeler: new label for root scripts

---

.github/labeler.yml

Apparently things starting with an asterisk are aliases in YAML. Explicitly encode as strings to avoid this.

Labeler: use comments to avoid aliases

---

tests/datasets/test_chesapeake.py
torchgeo/datasets/chesapeake.py

Closes #253
Some plots for different combinations of layers:

Adding plotting to ChesapeakeCVPR dataset

---

torchgeo/trainers/classification.py
torchgeo/trainers/detection.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py

@austinmw can you see if this fixes #825?

Trainers: fix plotting file handle leak

---

torchgeo/datasets/vaihingen.py

The current documentation contained a dead link so I replaced it and additionally added a link to the download page.

Replace dead link in Vaihingen dataset documentation

---

torchgeo/datasets/etci2021.py

Fix the ETCI 2021 Data loader by removing glob for each folder
I tried ETCI2021DataModule (on Mac), then found a bug for loading the images.
The loaded images are sometimes not correct by each sorted glob
You can find the image file paths are not same (of vv and water_mask) in attached result.
This PR changes the loader will do sorted glob once in vv folder, and then use it for others.

Fix a bug for ETCI2021 loader

---

torchgeo/datasets/astergdem.py

The "Aster Global Digital Elevation Model Dataset" is wrongly named "Aster Global Digital Evaluation Model Dataset". 
This PR fixes the name in the datasets' docstring.

Evaluation -> Elevation

---

tests/datasets/test_geo.py
torchgeo/datasets/geo.py

This PR adds the feature described in #867
Closes #867

Add transforms to UnionDataset and IntersectionDataset

---

torchgeo/trainers/classification.py
torchgeo/trainers/segmentation.py

- I thought it would be useful to add some documentation to the trainers, just to clarify how flexible they are and the wide choices of models they support without someone having to dig.
- The documentation for `ClassificationTask` states that possible weights are `Either “random”, “imagenet_only”, “imagenet_and_random”, or “random_rgb”` but only "imagenet" or "random" work otherwise you get an error, so I corrected the documentation for that
- In the documentation there were keyword args missing that were actually necessary to use the task with a trainer, so I added documentation for the required keywords

Docs/trainers for Classification and Segmentation Task

---

requirements/docs.txt

Documentation is failing to build on recent PRs:
```
WARNING: Pygments lexer name 'ipython3' is not known
```
I have no idea what changed since we lock down all direct dependencies. We'll see if this fixes the issue.
Related to https://github.com/spatialaudio/nbsphinx/issues/24.

Docs: fix broken build

---

tests/trainers/test_segmentation.py
torchgeo/trainers/segmentation.py

Closes #813. This PR adds a `predict_step` method to `SemanticSegmentationTask` so that users can utilize PyTorch Lightning's `trainer.predict()` function which will automatically loop and predict over a PyTorch DataLoader e.g.:
Added a note to the docstring for users to override this if they have many images or the images are large.
```python

add predict_step to SemanticSegmentationTask

---

conf/landcoverai.yaml
torchgeo/datamodules/landcoverai.py

Currently we add 1 to the LandCover.AI class indices. This causes several problems:
- We don't ignore the resulting 0 class index in training so the default train configuration doesn't work
- torchmetrics doesn't compute mIoU correctly because it thinks we have 6 classes (but we only have 5)
- Plotting doesn't work in the validation step of training
I don't see any upside to adding 1, so I removed it!

Fix landcoverai datamodule

---

tests/datasets/test_benin_cashews.py
tests/datasets/test_seco.py
torchgeo/datasets/benin_cashews.py
torchgeo/datasets/cloud_cover.py
torchgeo/datasets/cv4a_kenya_crop_type.py
torchgeo/datasets/eurosat.py
torchgeo/datasets/seco.py
torchgeo/datasets/sen12ms.py
torchgeo/datasets/sentinel.py
torchgeo/datasets/so2sat.py
torchgeo/datasets/zuericrop.py

There seems to be a 50/50 mix of `RGB_BANDS`/`ALL_BANDS` and `rgb_bands`/`all_bands` in our datasets. The `GeoDataset` base class uses lowercase, so this PR changes all other datasets to match. From what I can tell, [PEP-8](https://peps.python.org/pep-0008/) doesn't seem to distinguish between class attributes and instance attributes, so I'm not sure if these are considered variables or global variables.
@ashnair1 not sure if this affects #687

Datasets: consistent capitalization of band names

---

train.py

According to the [docs](https://pytorch-lightning.readthedocs.io/en/stable/common/evaluation_intermediate.html), calling `trainer.test(model=model)` will test using the current latest weights of a model. Changing this to `trainer.test(ckpt_path="best")` will use the previous best weights of the model used in the `trainer.fit()` call.

Test using best checkpoint

---

pyproject.toml

I haven't yet figured out why we don't see this issue in CI, but locally with the exact same versions of tensorboardX and protobuf I see:
```console
$ pytest
...
tests/trainers/test_segmentation.py:11: in <module>
from pytorch_lightning import LightningDataModule, Trainer
../.spack/.spack-env/view/lib/python3.10/site-packages/pytorch_lightning/__init__.py:35: in <module>
from pytorch_lightning.callbacks import Callback  # noqa: E402
../.spack/.spack-env/view/lib/python3.10/site-packages/pytorch_lightning/callbacks/__init__.py:28: in <module>
from pytorch_lightning.callbacks.pruning import ModelPruning
../.spack/.spack-env/view/lib/python3.10/site-packages/pytorch_lightning/callbacks/pruning.py:31: in <module>
from pytorch_lightning.core.module import LightningModule …
```

pyproject.toml: silence protobuf deprecation warning

---

torchgeo/datasets/nasa_marine_debris.py

`draw_bounding_boxes` raises a warning if no boxes are passed. PR fixes this by calling the function only if `sample["prediction_boxes"]` has non zero elements.

Fix for warning raised if model outputs no box predictions

---

torchgeo/datamodules/deepglobelandcover.py
torchgeo/datamodules/potsdam.py
torchgeo/datamodules/vaihingen.py
torchgeo/datasets/cyclone.py
torchgeo/datasets/gid15.py
torchgeo/models/rcf.py
torchgeo/samplers/batch.py
torchgeo/samplers/single.py

pydocstyle's support for Google-style docstring checking has been broken for a long time: https://github.com/PyCQA/pydocstyle/issues/459. I tested out https://github.com/PyCQA/pydocstyle/pull/589 which fixes this issue and discovered the following mistakes in our docstrings. I'm not sure if Google's style guide actually requires Args/Returns to come last, but the `Returns;` mistakes are real and [affected our docs](https://torchgeo.readthedocs.io/en/stable/api/datasets.html#torchgeo.datasets.GID15.plot).

Fix mistakes caught by pydocstyle convention PR

---

.gitignore

The default log directory of PyTorch Lightning is `lightning_logs`. We should ignore it.

.gitignore: ignore lightning_logs directory

---

docs/api/vit_pretrained_weights.csv

Wish there was a way to link to the enum itself so we can enforce that they are named correctly, but it doesn't seem to show up in the docs.

Fix ViT weight names in docs

---

.github/labeler.yml

Dependabot adds this label when it creates a PR, but we should also use it when one of these files is manually updated.

Labeler: add labels to dependency files

---

torchgeo/datasets/eurosat.py

Change https to http as the source SSL certificate is not valid anymore
Fixes #1064

Fix SSL issue with EuroSAT

---

.github/workflows/tests.yaml

See https://github.com/codecov/codecov-action/issues/903. I'm hoping this fixes our intermittent codecov issues.
Still need to add the secret to our repo, need to get access first.

Codecov: use repository upload token

---

torchgeo/datasets/eurosat.py

See https://github.com/phelber/EuroSAT/issues/10 for details. An added bonus of switching to Hugging Face is faster downloads: 3m 7s instead of 4m 11s.
Fixes #1064, reverts #1065
@julien-blanchon

EuroSAT: redistribute on Hugging Face

---

torchgeo/datasets/ucmerced.py

This was our only remaining dataset distributed via HTTP instead of HTTPS.
The data used to create this dataset is released under the [public domain](https://www.usgs.gov/faqs/what-are-terms-uselicensing-map-services-and-data-national-map) and the author adds no additional restrictions on the dataset. Got permission from Shawn Newsam to redistribute the dataset on Hugging Face via email.
Comparison of download times:
* Before: 55 sec
* After: 27 sec

UC Merced: redistribute on Hugging Face

---

.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml

See https://github.com/actions/setup-python and https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
See https://github.com/actions/setup-python/issues/330#issuecomment-1416883170 for a writeup from Adam about the speedup from this PR.

CI: cache pip installs

---

setup.cfg

This adds an "all" extra that allows you to install all optional dependencies. The following:
```console
$ pip install torchgeo[all]
```
is now equivalent to:
```console
$ pip install torchgeo[datasets,docs,style,tests]
```
Note that this requires pip 21.2+. Users on older versions of pip can still install torchgeo normally, but won't be able to install `torchgeo[all]`.
See https://hynek.me/articles/python-recursive-optional-dependencies/.

One extra to rule them all

---

.github/workflows/labeler.yml
.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml

See [the docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow).
If a new commit is pushed, there's no reason to finish jobs for old commits. RtD CI already does this.
The name of the concurrency group seems rather finicky. Other users recommend [something else]( https://stackoverflow.com/a/72408109/5828163). Spack uses [yet another option](https://github.com/spack/spack/pull/32361/files#r964394342). It's unclear to me which is required. I suggest starting simple and adding complexity when needed.

CI: cancel in-progress jobs when new commit

---

tests/trainers/test_byol.py
tests/trainers/test_classification.py
tests/trainers/test_regression.py
tests/trainers/test_utils.py
torchgeo/trainers/byol.py
torchgeo/trainers/utils.py

This PR closes #1049 , by implementing Isaac's [solution](https://github.com/microsoft/torchgeo/issues/1049#issuecomment-1406949155).

Fix load_state_dict for all timm models

---

experiments/run_chesapeakecvpr_models.py

Still not quite sure why this happened, but I ran `pytest` on our new cluster and it picked up the `test_chesapeakecvpr_models.py` script and failed on an import that no longer exists. Renamed the file to avoid this and fixed the import.

Chesapeake CVPR experiment: fix import

---

.github/dependabot.yml
environment.yml
setup.cfg
tests/datasets/test_benin_cashews.py
tests/datasets/test_cloud_cover.py
tests/datasets/test_cv4a_kenya_crop_type.py
tests/datasets/test_cyclone.py
tests/datasets/test_nasa_marine_debris.py
torchgeo/datasets/benin_cashews.py
torchgeo/datasets/cloud_cover.py
torchgeo/datasets/cv4a_kenya_crop_type.py
torchgeo/datasets/cyclone.py
torchgeo/datasets/nasa_marine_debris.py

Quick changes to several datasets and the tests to support the new download file structures in `radiant-mlhub>=0.5`.
Quick changes for now. Currently no checksum checking for the dataset since `radiant-mlhub` just downloads the individual files directly. Any ideas how I can check for partial dataset downloads? `radiant-mlhub` says it will auto-resume dataset downloads if requested but this code does not currently check or ask it to resume. 
Closes #711 
Closes #1101

Support for radiant-mlhub 0.5+

---

docs/api/resnet_pretrained_weights.csv
docs/api/vit_pretrained_weights.csv
torchgeo/models/resnet.py
torchgeo/models/vit.py

This PR includes the following changes:
All old weights still exist at the same URLs for backwards compatibility. All new weights should follow this `<name>-<sha256>.pth` format.
References:
* https://github.com/pytorch/vision/issues/7210
* https://github.com/pytorch/vision/pull/7219
* https://pytorch.org/docs/stable/hub.html#torch.hub.load_state_dict_from_url
We won't actually be able to use this checksum until torchvision 0.15.0, but might as well do the heavy lifting now.

Weights: add sha256 suffix

---

torchgeo/datasets/bigearthnet.py

It seems like the mapping from 43 to 19 classes in the BigEarthNet dataset code is incorrect. 
**Example**
The below image corresponds to the RGB visualization of S2B_MSIL2A_20180502T093039_42_25. The provided textual labels are 'Broad-leaved forest', 'Natural grassland', and 'Transitional woodland/shrub'. Per the mapping provided [here](https://github.com/microsoft/torchgeo/blob/main/torchgeo/datasets/bigearthnet.py#L145-L190) , this corresponds to indices 5, 24, and 39. After converting these from 43 class labels to 19 class labels using the [label converter](https://github.com/microsoft/torchgeo/blob/main/torchgeo/datasets/bigearthnet.py#L193-L226), we end up with 5 being discarded, 24 (Natural grassland) mapping to 10 (Mixed forest) and 39 (Transitional woodland/shrub) mapping to 17 …

Change BigEarthNet class mapping order to match original code

---

tests/datasets/test_geo.py
tests/datasets/test_landsat.py
torchgeo/datasets/geo.py
torchgeo/datasets/landsat.py

This PR fixes multiple bugs related to band indexing in RasterDataset:
The fix was simple. We don't need to compute `band_indexes` unless `separate_files` is False.
Confirmed that the tests I added fail without this fix, so this bug shouldn't pop back up in the next release.
Should we rename Landsat's `all_bands` to `default_bands`? In #504 we added support for all Level-1 and Level-2 products and decided not to list every possible band name because there are way too many and I can't easily confirm what they were all the way back to Landsat 1.
This bug was introduced in #687, apologies for not catching this during review.
Fixes #1134 @TolgaAktas

RasterDataset: fix band indexing bug

---

torchgeo/datasets/usavars.py

The current implementation of the USAVars dataset only suppports three labels like the documentation says, but as default all labels are included, so if you run the dataset with default arguments, errors will be thrown. 
This PR has two simple changes:
- `ALL_LABELS` to only be the available labels
- documentation indent for proper bullet points rendering on docs

Usa vars label bug

---

tests/trainers/test_byol.py
tests/trainers/test_classification.py
tests/trainers/test_regression.py
tests/trainers/test_segmentation.py
tests/trainers/test_utils.py

These fake models have nothing to do with testing `torchgeo/trainers/utils.py` and should either be in the files where they are used or in `conftest.py`.

Trainers: refactor tests

---

tests/datasets/test_eurosat.py
tests/trainers/test_classification.py
torchgeo/datamodules/__init__.py
torchgeo/datamodules/eurosat.py
torchgeo/datasets/__init__.py
torchgeo/datasets/eurosat.py

This is a subset of the EuroSAT MS dataset containing only 100 images. Yes, you heard that right, 100 images. This dataset maintains the 60-20-20 train-val-test split from https://arxiv.org/abs/1911.06721. There are 10 images (6 train, 2 val, 2 test) for all 10 classes, for a total of 100 images.
Our tutorials download a lot of data. So much in fact that we crash the meager 14 GB SSD in our [GitHub Actions runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources), causing our notebook tests to fail for the last year or so. Between NAIP, Chesapeake, Sentinel, EuroSAT, and TropicalCyclone, we're talking several minutes of downloads. The TropicalCyclone download doesn't even work unless you sign up for an API …

EuroSAT100: add new dataset/datamodule

---

torchgeo/trainers/classification.py
torchgeo/trainers/detection.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py

Fixes #1143 
Can be tested by running the pretrained weights or trainers tutorials and replacing:
```
pip install torchgeo
```
with
```
pip install git+https://github.com/microsoft/torchgeo.git@fixes/csv-logger
```

Trainers: fix support for non-TensorBoardLogger

---

docs/index.rst
docs/tutorials/benchmarking.ipynb
docs/tutorials/getting_started.ipynb
docs/tutorials/indices.ipynb
docs/tutorials/trainers.ipynb
docs/user/contributing.rst
torchgeo/datasets/chesapeake.py
torchgeo/datasets/cv4a_kenya_crop_type.py
torchgeo/datasets/enviroatlas.py
torchgeo/datasets/eudem.py
torchgeo/datasets/forestdamage.py
torchgeo/datasets/naip.py
torchgeo/datasets/potsdam.py
torchgeo/datasets/resisc45.py
torchgeo/datasets/seco.py
torchgeo/datasets/sen12ms.py
torchgeo/datasets/vhr10.py
torchgeo/datasets/zuericrop.py
torchgeo/trainers/byol.py
torchgeo/trainers/classification.py
torchgeo/trainers/regression.py
torchgeo/transforms/indices.py

TIL you can run:
```console
$ cd docs
$ make linkcheck
```
and Sphinx will parse and check all external links in your docs and warn you which links are broken. Unfortunately there are too many false positives to make this a CI test, but this may be something we want to check before each release.

Fix broken URLs

---

tests/trainers/test_detection.py
torchgeo/trainers/detection.py

Same idea as https://github.com/microsoft/torchgeo/pull/344, but for the object detection tests.
See https://github.com/microsoft/torchgeo/issues/1088 for discussion.
On my machine this reduced the time taken for `tests/trainers/test_detection.py` from 22 seconds to 11 seconds.

Speed up detection tests

---

torchgeo/datasets/landsat.py

For Landsat, B8–B11 only exist for raw imagery and top of atmosphere reflectance, not surface reflectance. I still think it makes sense to default to surface reflectance, but we should not include bands that don't exist for it.
At least on Google Earth Engine (GEE), Landsat 1–5 Multispectral Scanner (MSS) do not have surface reflectance, so default to the band names for raw imagery.
References:
* [SR](https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LC09_C02_T1_L2)
* [TOA](https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LC09_C02_T1_TOA)
* [raw](https://developers.google.com/earth-engine/datasets/catalog/LANDSAT_LC09_C02_T1)

Landsat: better default bands

---

pyproject.toml
tests/datamodules/test_geo.py
tests/datamodules/test_oscd.py
tests/trainers/test_byol.py
tests/trainers/test_classification.py
tests/trainers/test_detection.py
tests/trainers/test_regression.py
tests/trainers/test_segmentation.py

Starting with Lightning 2.0, `Trainer` now defaults to `accelerator="auto"`, meaning it searches to see if any GPU/MPS device is available. While this works fine with CUDA, the MPS backend is still missing implementations of many operators, so the tests will fail. We should force the tests to use the CPU to ensure that they always pass, even on macOS. We don't see this issue in CI because the GitHub runner is an old x86_64 Mac and doesn't support MPS.

Fix tests when PyTorch built with MPS support

---

tests/models/test_resnet.py
tests/models/test_vit.py
torchgeo/datamodules/seco.py
torchgeo/models/resnet.py
torchgeo/models/vit.py

Our pre-trained models come with preprocessing transforms that should be used to normalize and reshape images used with them. However, these transforms don't actually run. This PR fixes them and adds tests to ensure that all transforms actually work.

Models: fix preprocessing transforms

---

torchgeo/datasets/cdl.py

The USDA releases CDL data every year in January of the following year.

CDL: add 2022 checksum

---

torchgeo/datasets/geo.py

Datasets like Landsat have different band names for TOA and SR products. Although we default to SR, many users use TOA data and are confused when no data is found because they didn't change the default `bands`. This PR adds `bands` to the error message, which should hopefully make it easier to realize that `bands` needs to be changed. To test, run this script:
```python
from torchgeo.datasets import Landsat8
Landsat8("data/landsat8/toa")
```
Doesn't give any reason why no data was found:
```
Traceback (most recent call last):
File "/Users/Adam/torchgeo/test.py", line 3, in <module>
Landsat8("data/landsat8/toa")
File "/Users/Adam/torchgeo/torchgeo/datasets/landsat.py", line 85, in __init__
super().__init__(root, crs, res, bands, transforms, cache)
File …
```

RasterDataset: better error message when no data found

---

tests/datasets/test_geo.py
tests/datasets/test_splits.py
torchgeo/datasets/geo.py

To illustrate why this is needed, create two directories containing non-overlapping images, and run the following script:
```python
from torch.utils.data import DataLoader
from torchgeo.datasets import Landsat8
from torchgeo.samplers import RandomGeoSampler
bands = ["B1", "B2", "B3"]
ds1 = Landsat8("data/dir1", bands=bands)
ds2 = Landsat8("data/dir2", bands=bands)
ds = ds1 & ds2
rs = RandomGeoSampler(ds, 256, 10)
dl = DataLoader(ds, sampler=rs)
for batch in dl:
pass
```
The previous error message was completely useless, and led to much confusion due to https://github.com/Toblerity/rtree/issues/204:
```
Traceback (most recent call last):
File "/Users/Adam/torchgeo/test.py", line 12, in <module>
rs = RandomGeoSampler(ds, 256, 10)
File "/Users/Adam/torchgeo/torchgeo/samplers/single.py", line …
```

IntersectionDataset: better error message when no overlap

---

README.md

Noticed some things that were out of date.

README: update Lightning trainer examples

---

torchgeo/datasets/geo.py

No idea why I added this, but it doesn't seem necessary unless one of the bands contains a glob character, which isn't something I think we want to support. This may make data loading marginally faster.

RasterDataset: remove unnecessary glob

---

.github/workflows/release.yaml
.github/workflows/tutorials.yaml
environment.yml
requirements/min-reqs.old
requirements/required.txt
requirements/tests.txt
setup.cfg

TorchGeo does not import or require either of these dependencies. The only thing these deps are required for is our trainer tests, for [a single notebook](https://github.com/microsoft/torchgeo/pull/1189), and for train.py and friends. None of these files get installed when you run `pip install torchgeo`, so the dependency shouldn't be required.
Omegaconf was always an issue (every time you update the conda-forge recipe it complains that it isn't used), but the lightning/tensorboard issue is relatively new. Starting with lightning 1.9, tensorboard was moved from a required dependency to [an optional extra](https://github.com/Lightning-AI/lightning/pull/16349). However, our tests need tensorboard for coverage, so we added a dependency on `lightning[extra]` to pull in tensorboard. However, …

Deps: make omegaconf/tensorboard optional

---

train.py

Fixes an issue where mode defaulted to "min". This caused an issue while training a detection model where the best model was (incorrectly) thought to be the one with the lowest MAP.

Specify mode in ckpt callback

---

requirements/min-reqs.old

Discovered by @yichiac.
See https://github.com/microsoft/torchgeo/actions/runs/4670725252/jobs/8270814132?pr=1229 for an example of the error that happens without this.
Older versions of lightning didn't properly list their dependencies until https://github.com/Lightning-AI/lightning/pull/16302. I'm guessing a different dependency was indirectly installing websockets before, but a new release dropped this dependency, so lightning started to fail all of a sudden. Not really preventable unless we want to use pip lock files and have dependabot update every indirect dep every day.
Alternative is to require a newer version of lightning. I don't see a great reason to limit ourselves, and the workaround is simple.

Fix minimum tests, lightning missing websockets dep

---

tests/trainers/test_classification.py
tests/trainers/test_regression.py

Reverts microsoft/torchgeo#1229
This was not the right approach. It fixes the tests for the SeCo weights, but breaks the tests for all other weights. The correct fix is to ensure that the SeCo weights can be loaded without warnings.

Revert "Tests: downloaded weights have different number of classes"

---

.github/workflows/tests.yaml

Honestly not sure how this ever worked. My text editor marks `\b` as the ASCII backspace character. Using single quotes instead of double quotes avoids backslash being interpreted as a special character. I'm guessing the reason it works is because the YAML interpreter GitHub uses doesn't register `\b`? Anyway, this fix makes my editor happy.

Windows CI: replace pacman with choco

---

torchgeo/datasets/western_usa_live_fuel_moisture.py

I had switched the lat/lon from the dataset, which I discovered when trying to do the following plot:
```
import matplotlib.pyplot as plt
import geopandas
import geoplot as gplt
target = ds.dataframe["percent(t)"]
fig, ax = plt.subplots(ncols=2)
gdf = geopandas.GeoDataFrame(
target,
geometry=geopandas.points_from_xy(self.dataframe.lon, self.dataframe.lat),
)
contiguous_usa = geopandas.read_file(gplt.datasets.get_path('contiguous_usa'))
gplt.polyplot(contiguous_usa, ax=ax[0])
gplt.pointplot(
gdf, hue="percent(t)", legend=True, ax=ax[0],
)
ax[0].set_title(
f"Spatial Distribution of Live Fuel Moisture for the full dataset."
)
ax[1].violinplot(self.dataframe["percent(t)"].values)
ax[1].set_title("Distribution of Moisture Percentage Full dataset.")
ax[1].set_ylabel("Live Fuel Moisture …
```

Fix lat/lon in Western USA Live Fuel Moisture Dataset.

---

torchgeo/datamodules/chesapeake.py
torchgeo/datamodules/geo.py
torchgeo/datamodules/l7irish.py
torchgeo/datamodules/l8biome.py
torchgeo/datamodules/naip.py

#755 added a default length for all GeoSamplers. We should use this by default instead of requiring users to know how long an epoch should be.
@yichiac @shradhasehgal

GeoDataModules: automatically infer length by default

---

docs/conf.py
environment.yml
requirements/min-reqs.old
requirements/required.txt
setup.cfg
tests/datamodules/test_utils.py
torchgeo/datamodules/cyclone.py
torchgeo/datamodules/sen12ms.py
torchgeo/datamodules/utils.py

We only use sklearn for GroupShuffleSplit. Reimplementing our own version to remove this dependency.

Remove scikit-learn

---

torchgeo/trainers/segmentation.py

Adding ability to pass in class weights into cross entropy loss.

added class_weights for cross entropy loss to segmentation.py

---

docs/api/non_geo_datasets.csv

I would like to fix a small typo in the documentation. The UC Merced land-use dataset consists of 2,100 images, not 21,000 (although it would be nice if it were more extensive). As far as I've seen, n=21,000 is only referenced in the table, while the actual UC Merced dataset class refers to the correct n=2,100.

fix typo in docs: ucmerced n=2,100 not n=21,000

---

docs/api/datamodules.rst
torchgeo/datamodules/__init__.py
torchgeo/datamodules/geo.py

A lot of the code in our base classes was shared, so I aggregated it.
Originally I was just planning on adding better error messages, but figured I would do this first.

DataModule: common base class to reduce code duplication

---

experiments/download_ssl4eo.py

Occasionally (< 1% of the time) images will be smaller than the radius (e.g., 263 instead of 264) due to reprojection. This pads those images to match the expected size so that all bands can be stacked into a single image and all images have the same size.

SSL4EO download script: pad images and increase stability

---

tests/transforms/test_color.py
torchgeo/transforms/__init__.py
torchgeo/transforms/color.py

Each of these images are scaled from 0–1 for plotting, so the brightness of the image may not be comparable.

RandomGrayscale: add new transform

---

tests/trainers/test_regression.py
torchgeo/trainers/regression.py

Similarly to #1046, this adds the ability to load pretrained encoder weights from our weight enums and checkpoint files to `PixelwiseRegressionTask`.

PixelwiseRegressionTask pretrained weights

---

experiments/ssl4eo/download_l5_raw.sh
experiments/ssl4eo/download_l7_l1.sh
experiments/ssl4eo/download_l7_l2.sh
experiments/ssl4eo/download_l8_l1.sh
experiments/ssl4eo/download_l8_l2.sh
experiments/ssl4eo/download_ssl4eo.py
experiments/ssl4eo/sample_30.sh
experiments/ssl4eo/sample_60.sh

#1223 included https://github.com/microsoft/torchgeo/pull/1223/commits/53a776e67f5a7abb24d38c31dce95e03b670029e, which hacked the script to resize the panchromatic band on Landsat 8. Unfortunately, this resulted in the script only working for Landsat 8 Level-1 data. This PR further generalizes this feature to support both resampling all bands to a single resolution and keeping all bands in their original resolution. It also includes scripts to bash scripts to download data for each satellite.
I tested all scripts to make sure they are able to download data and the images look correct (all bands have the same dimensions and spatial extent). There are still a few garbage images (clouds, nodata pixels, noise) but there isn't much we can do about that at this stage.
Note that there is almost …

SSL4EO: more generic download script

---

torchgeo/transforms/color.py

Follow up to #1301.
Apparently square brackets don't need to be escaped: https://torchgeo.readthedocs.io/en/latest/api/transforms.html#torchgeo.transforms.RandomGrayscale

RandomGrayscale: fix math in docs

---

experiments/ssl4eo/sample_conus.py

"Commonwealth of the Northern Mariana Island" was missing an S for "Islands".

Typo in sample_conus.py script

---

experiments/ssl4eo/delete_mismatch.py
experiments/ssl4eo/delete_mismatch.sh

Given directories of downloaded data, this script deletes any scenes that are not common between all datasets. This lets us build a parallel corpus for all satellites. We delete all locations that are not shared, and all times that are not shared between Level-1 and Level-2 within a single satellite (L7 and L8 are from different decades so it doesn't make sense to require the same dates).
I didn't try parallelizing this script. I'm not sure how long it will take to delete all files, but a dry run on 600K L8 files takes 3.5 min (99% of time spent on looping over all directories to compare dates).
Unfortunately, this script requires all datasets to be on one system. We have enough storage/inodes for this, but transferring everything to our cluster will be slow. Alternatively, we could …

Add script to delete mismatched scenes

---

experiments/ssl4eo/download_ssl4eo.py
experiments/ssl4eo/sample_ssl4eo.py

This PR contains the following improvements to our sampler script:
I wanted to add `np.random.seed(0)` to the script, but that would result in the first `indices_range[1]` samples we draw already being present in the resume file, meaning we would just skip them. I don't know of an easy way to update the random seed to the prior state without saving it.
@wangyi111

Various fixes to SSL4EO sampler

---

pyproject.toml
requirements/required.txt
tests/conf/chesapeake_cvpr_prior_moco.yaml
tests/conf/seco_moco_1.yaml
tests/conf/seco_moco_2.yaml
tests/conf/ssl4eo_s12_moco_1.yaml
tests/conf/ssl4eo_s12_moco_2.yaml
tests/trainers/test_moco.py
torchgeo/trainers/__init__.py
torchgeo/trainers/moco.py
torchgeo/trainers/simclr.py
train.py

Add MoCo trainer

---

experiments/ssl4eo/delete_mismatch.sh
experiments/ssl4eo/download_l5_l1.sh

We we're planning on using L7 as a proxy for L5. On paper, all we have to do is drop the panchromatic band, and decrease resolution of the thermal band. But GEE splits the thermal band into low-gain and high-gain, only for L7 TOA. So we need to download a separate L5 TOA dataset.

Landsat 5 TOA also needs to be downloaded

---

tests/samplers/test_single.py
torchgeo/datasets/geo.py
torchgeo/samplers/single.py

Partially reverts #630. See #1245 for motivation.
@remtav

GridGeoSampler: don't change stride of last patch

---

experiments/ssl4eo/compress_dataset.py
experiments/ssl4eo/compress_l5_l1.sh
experiments/ssl4eo/compress_l7_l1.sh
experiments/ssl4eo/compress_l7_l2.sh
experiments/ssl4eo/compress_l8_l1.sh
experiments/ssl4eo/compress_l8_l2.sh

This is hopefully the final script we need for dataset preprocessing. It allows us to map from the raw float32 files we downloaded to uint8 files while still capturing the majority of information. Reflectance bands were scaled using GEE visualization parameters. Temperature bands were scaled using NASA visualization parameters. Validation was done by computing statistics on the new datasets and visualizing the resulting bands in QGIS. Dataset size reduction is on the order of 15% of the original size.

Add script to compress dataset files

---

experiments/ssl4eo/download_l7_l2.sh
experiments/ssl4eo/download_l8_l2.sh
experiments/ssl4eo/download_ssl4eo.py

This PR partially reverts #1310.
During downloading, we discovered that ignoring images containing nodata pixels slightly reduces the number of L8 L1 images we download, and drastically reduces the number of L8 L2 images we download. Visual inspection of the L8 L2 images we were skipping shows that those images are perfectly fine. I'm guessing they were removed because the L1 -> L2 process resulted in values that were clipped, or there's a 1 pixel border of nodata pixels, or something like that.
_If_ we need to download more images (e.g., for SSL4EO-L v2 or SSL4EO-M), we'll want to use a different strategy:
1. Download TOA for L5, L7, L8, filtering clouds and nodata pixels
2. Delete all scenes without matching locations
3. Repeat 1 and 2 until we have 250K+ scenes
4. Download SR for L5, …

SSL4EO download script: optionally download nodata pixels

---

experiments/ssl4eo/chip_landsat_downstream.py

This PR adds a script to create matching mask chips for downstream evaluation tasks based on CONUS data. @adamjstewart 
Remaining Questions:
- what should be the proper directory structure for a sample, still the numerate/landsat_id/*.tif?
- how to add the no-data mask?
Issues:
- Currently all masks I am chipping are just plain zeros :/ and not sure why

Create matching CDL/NLCD chips for downstream tasks

---

torchgeo/trainers/moco.py
torchgeo/trainers/simclr.py

The recommended learning rates I initially had are all wrong.
The MoCo v1 paper explicitly mentions using an initial lr of 0.03 for a batch size of 256. They also mention using linear lr scaling (i.e., lr = 0.03 * batch_size / 256). I couldn't find any mention of learning rate in the MoCo v2 paper, but the MoCo v3 paper also mentions using linear lr scaling.
The MoCo v1/v2 GitHub uses an lr of 0.03 and bs of 256, so that matches the v1 paper. The MoCo v3 GitHub uses an lr of (0.6 x batch_size / 256), so that was already correct.
The SimCLR v1 paper uses a lr of (0.3 * batch_size / 256), but mentions that this works better for SGD/Momentum based optimizers, while a lr of (0.075 * sqrt(batch_size)) works better for the LARS optimizer. The SimCLR v2 paper uses a lr of (0.1 * …

MoCo/SimCLR: better default lr

---

docs/api/resnet_pretrained_weights.csv
torchgeo/models/resnet.py

This PR adds the ResNet50 RGB weights trained on fMoW (mostly Maxar WorldView imagery) using the  [Geography Aware Self-supervised Learning (GASSL)](https://arxiv.org/abs/2011.09980) method. This is basically a modified MoCo-v2 with Geolocation as a pretext task (Geo) as well as temporal pairs contrastive learning (TP).
Weights taken from [this repo](https://github.com/sustainlab-group/geography-aware-ssl) and uploaded to huggingface.
Adding these weights is essential since it's being compared as a baseline in both the [SatMAE](https://arxiv.org/abs/2207.08051) and [Scale-MAE](https://arxiv.org/abs/2212.14532) papers.

GASSL ResNet50 Weights

---

tests/datasets/test_cdl.py
torchgeo/datasets/cdl.py

This PR adds `years` argument to select a number of years for which to download CDL or use CDL so the user doesn't have to download all 15 years. This is how we decided to implement it for NLCD as well.

Add year filter functionality CDL

---

tests/trainers/test_byol.py
tests/trainers/test_classification.py
tests/trainers/test_moco.py
tests/trainers/test_regression.py
tests/trainers/test_segmentation.py
tests/trainers/test_simclr.py

We don't need to test the BYOL trainer with every set of pretrained weights (we don't actually need to involve pretrained weights at all).

Test fewer models in trainers to avoid exceeding RAM

---

.github/dependabot.yml
.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml
.github/workflows/tutorials.yaml
.readthedocs.yaml
requirements/datasets.txt
requirements/required.txt
setup.cfg

Now that PyTorch 2.0 is out, which adds Python 3.11 support, we should see how many of our other dependencies support Python 3.11 and make sure TorchGeo supports it as well. This PR adds Python 3.11 to our unit tests.
Still waiting on the following dependencies:

Test Python 3.11

---

torchgeo/datasets/dfc2022.py

`interpolation=None` is equivalent to the default, which is `interpolation="antialiased"`.

DFC2022: avoid interploation in colormap

---

experiments/ssl4eo/sample_ssl4eo.py

From https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nlargest.html:
> This method is equivalent to `df.sort_values(columns, ascending=False).head(n)`, but more performant.
@wangyi111

sample_ssl4eo: faster top 10K population cities

---

experiments/ssl4eo/plot_landsat_timeline.py

The goal is to get something similar to [this](https://www.usgs.gov/media/images/landsat-missions-timeline):
Here is what I have so far:
Crosshatched regions represent partial or complete sensor failure.

Add script to plot Landsat mission timeline

---

conf/l7irish.yaml
conf/l8biome.yaml
conf/ssl4eo_benchmark_etm_sr_cdl.yaml
conf/ssl4eo_benchmark_etm_sr_nlcd.yaml
conf/ssl4eo_benchmark_etm_toa_cdl.yaml
conf/ssl4eo_benchmark_etm_toa_nlcd.yaml
conf/ssl4eo_benchmark_oli_sr_cdl.yaml
conf/ssl4eo_benchmark_oli_sr_nlcd.yaml
conf/ssl4eo_benchmark_oli_tirs_toa_cdl.yaml
conf/ssl4eo_benchmark_oli_tirs_toa_nlcd.yaml
conf/ssl4eo_benchmark_tm_toa_cdl.yaml
conf/ssl4eo_benchmark_tm_toa_nlcd.yaml

@yichiac @shradhasehgal I believe these are the config files we want. I changed several things from #1343 and #1346:
The `run_*_experiments.py` files are basically identical for all datasets so I didn't bother including those. Honestly, we should consider removing those and making one script to rule them all.

Add config files for SSL4EO-L downstream tasks

---

experiments/ssl4eo/chip_landsat_downstream.py
torchgeo/datasets/ssl4eo_benchmark.py

We were using the mask from NLCD/CDL but not copying the nodata pixels from the Landsat 7 ETM+ SLC-off image. Therefore, the model was being penalized for not correctly predicting classes where it didn't even have imagery to use.
Example:

SSL4EO-L Benchmark ETM+: copy nodata pixels from img to mask

---

tests/trainers/test_segmentation.py
torchgeo/trainers/segmentation.py

Avoids ambiguous truth value `ValueError` when the class_weight input parameter is either a PyTorch tensor or a NumPy array.
Repro follows—also fails with `np.array` instead `torch.tensor`, succeeds with Python sequence.
```
import torch
from torchgeo.trainers.segmentation import SemanticSegmentationTask
SemanticSegmentationTask(
model='unet',
backbone='resnet101',
loss='ce',
learning_rate=0.01,
weights=None,
class_weights=torch.tensor([0.25, 0.5, 0.25]),
in_channels=1,
num_classes=3,
ignore_index=None
)
```
Expected:
```
<prints PyTorch model>
```
Actual:
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "<path>/torchgeo/torchgeo/trainers/segmentation.py", line 171, in __init__
self.config_task()
File "<path>/torchgeo/torchgeo/trainers/segmentation.py", line …
```

fix: Support tensors and arrays for class_weight

---

tests/datamodules/test_geo.py
torchgeo/datamodules/geo.py

Closes #1307 
This implementation defines two new helper functions:
* `_valid_attribute`: checks if at least one of the datasets or samplers has length > 0
* `_dataloader_factory`: defines a `*_dataloader` depending on the split
The former handles all error messages and provides more specific and helpful error messages. Another bonus is that we avoid the majority of code duplication in these base classes, chopping off 30+ lines of code.
@yichiac I know you've run into this error message too many times, hopefully this will help with debugging.

DataModules: improve error messages

---

tests/models/test_changestar.py
tests/models/test_fcsiam.py

It turns out that pytest has a builtin way to support parametrization cross products that's much simpler than creating our own cross products.

Use pytest parametrize cross product

---

.github/ISSUE_TEMPLATE/config.yml
README.md

TorchGeo has a Slack channel. We should advertise it better so anyone can join.
The badge can be viewed at https://github.com/adamjstewart/torchgeo/tree/github/slack.
Slack no longer supports permanent invite links, so this link will expire and need to be updated after 400 people join. I don't think that will happen any time soon but if someone says it doesn't work, that's what happened.

Advertise TorchGeo Slack

---

pyproject.toml
requirements/datasets.txt
requirements/min-reqs.old
requirements/required.txt
tests/datasets/test_eddmaps.py
tests/datasets/test_gbif.py
tests/datasets/test_idtrees.py
tests/datasets/test_inaturalist.py
tests/datasets/test_openbuildings.py
tests/datasets/test_reforestree.py
tests/datasets/test_seasonet.py
tests/datasets/test_usavars.py
tests/datasets/test_western_usa_live_fuel_moisture.py
torchgeo/datasets/eddmaps.py
torchgeo/datasets/gbif.py
torchgeo/datasets/idtrees.py
torchgeo/datasets/inaturalist.py
torchgeo/datasets/openbuildings.py
torchgeo/datasets/reforestree.py
torchgeo/datasets/seasonet.py
torchgeo/datasets/usavars.py
torchgeo/datasets/western_usa_live_fuel_moisture.py

Pandas is now used in 9 of our datasets, and 2 other datasets use csv but could use pandas instead. I think it's worth making pandas a required dependency. Also see discussion in #662. This lets us shave off 300 lines of code.

Promote pandas to a required dependency

---

.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml
.github/workflows/tutorials.yaml

We don't run `pip list` if we restore from cache, making it difficult to report and debug version issues. This PR fixes that.

CI: pip list even if restoring from cache

---

.pre-commit-config.yaml
pyproject.toml
requirements/min-reqs.old
tests/datasets/test_idtrees.py
tests/datasets/test_landcoverai.py

Some of our minimum version tests are being skipped. This doesn't ensure that our minimum versions actually work. Let's fix that.

Ensure that none of our minimum version tests are skipped

---

torchgeo/trainers/classification.py
torchgeo/trainers/detection.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py

Fixes #1551. See #1487 for discussion.
@gtgrp-user can you confirm this solves your issue? I never figured out how to test this in CI but it's obviously a bug and the fix is pretty simple.

Fix trainer support for datasets without a plot method

---

torchgeo/trainers/classification.py

Follow-up to #1221 
Closes #1287

ClassificationTask: add class_weights parameter

---

torchgeo/models/resnet.py
torchgeo/models/vit.py

Correct the seco weight names

---

torchgeo/datasets/l7irish.py
torchgeo/datasets/l8biome.py
torchgeo/datasets/nlcd.py

These datasets are all new in 0.5.0, no reason to document the fact that the parameter name changed.

Don't document param change for new datasets

---

.github/workflows/release.yaml
.github/workflows/tutorials.yaml
docs/tutorials/getting_started.ipynb
tests/datasets/test_advance.py
tests/datasets/test_skippd.py
tests/trainers/test_detection.py
tests/trainers/test_moco.py
tests/trainers/test_regression.py
tests/trainers/test_simclr.py
torchgeo/__init__.py
torchgeo/datamodules/chesapeake.py

0.5.0 release

---

README.md

Closes https://github.com/microsoft/torchgeo/issues/1626

Update info on LightningCLI

---

CITATION.cff
README.md

When running `cffconvert --validate`, we see a bunch of issues. They don't cause issues when rendering the citation, but might as well fix them.

Fix CITATION.cff format

---

.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml
.github/workflows/tutorials.yaml
pyproject.toml
requirements/min-reqs.old

Our CI has been dead in the water for the last 4 days. This PR fixes that. Specifically, this includes the following changes:
The result is that we're no longer MBs away from running out of space in any given PR.

CI: minimize storage usage

---

tests/datasets/test_mapinwild.py

We were only copying .zip files but we also need to copy .csv files. Without this, the tests were downloading an extra CSV file.
Relates to #1088, wish we had a better way to test this.
@burakekim

MapInWild: prevent download during testing

---

torchgeo/datamodules/eurosat.py

Bands are now used to update the `mean` and `std` attributes used in normalisation. 
Closes https://github.com/microsoft/torchgeo/issues/1634

EuroSATDataModule: set mean/std based on bands

---

.github/workflows/tests.yaml

CI is currently broken due to issues with `choco install unrar`. I informed the maintainers of that recipe. Until it gets fixed, we should consider using a different RAR backend. Rarfile supports many: https://pypi.org/project/rarfile/

CI: fix RAR backend installation

---

torchgeo/trainers/classification.py
torchgeo/trainers/detection.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py

Fixes an error that occurred when using Trainers with PyTorch DataLoaders instead of a Lightning DataModule.
-> as discussed in #1598

Fix all Trainers to support PyTorch DataLoaders

---

torchgeo/datasets/agb_live_woody_density.py
torchgeo/datasets/astergdem.py
torchgeo/datasets/cdl.py
torchgeo/datasets/chesapeake.py
torchgeo/datasets/cms_mangrove_canopy.py
torchgeo/datasets/esri2020.py
torchgeo/datasets/eudem.py
torchgeo/datasets/globbiomass.py
torchgeo/datasets/l7irish.py
torchgeo/datasets/l8biome.py
torchgeo/datasets/nlcd.py
torchgeo/datasets/openbuildings.py

Renamed ``root={self.paths}`` to ``paths={self.paths!r}``

Fixed ``path`` and ``root`` inconsistency.

---

tests/datamodules/test_levircd.py
torchgeo/datamodules/__init__.py
torchgeo/datamodules/levircd.py
torchgeo/datasets/levircd.py

Close https://github.com/microsoft/torchgeo/issues/1706

Add data module for LEVIR-CD+ dataset

---

torchgeo/datasets/ucmerced.py

**Description:**
Encountered an issue where ucmerced dataset images would render as blank after using the plot function and matplotlib to show the image.
**Issue:**
The underlying cause is that Matplotlib expects float values to be normalized between 0 and 1. However, the float tensor representing our image data occasionally contained values in the 0 to 255 range, leading to unexpected behavior in the rendering process.
**Resolution:**
A conditional check has been introduced. When the maximum value in the image tensor exceeds 1, the tensor is normalized by scaling down to the 0 to 1 range. This ensures compatibility with Matplotlib's expected float value range and resolves the issue of blank images.
**Outcome:**
With the proposed changes, images are displayed correctly, regardless of …

Fix for Blank Images in plot due to Float Tensor Ranges

---

docs/api/datamodules.rst
docs/api/datasets.rst
docs/api/non_geo_datasets.csv

I think we forgot to add the SSL4EO Benchmark Dataset/Datamodule to the Docs. Do you want to put entries for all possible constillations in the csv file?

Add SSL4EO-L Benchmark to docs

---

tests/conf/ssl4eo_l_moco_1.yaml
torchgeo/trainers/base.py
torchgeo/trainers/byol.py
torchgeo/trainers/classification.py
torchgeo/trainers/moco.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py
torchgeo/trainers/simclr.py

Trainers: skip weights and augmentations when saving hparams

---

.github/release.yml

See https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes for documentation.
This file lets us automatically generate Release Notes based on PR labels. In combination with the Labeler action, it ensures that all PRs make it into the Release Notes.
It's not perfect, and there will be many times when we have to edit things, but it gives us a start and saves us a lot time.

Automatically generate release notes

---

requirements/min-cons.old

The latest lightning-utilities release deprecates a feature that was used in old versions of lightning. Instead of ignoring it, let's prevent newer versions of lightning-utilities from being used in CI. Otherwise, it will eventually be removed and things will start to break.
Released [2 days ago](https://pypi.org/project/lightning-utilities/), which explains why our tests just started to break.

CI: fix lightning-utilities deprecation warning

---

torchgeo/datasets/sustainbench_crop_yield.py

Fixes #1754 -- the whole dataset is only 291Mb so we can safely load all of this in the constructor then just access it in `__getitem__` (this also only takes a few seconds at most).
This PR also updates the dataset to download the "soybeans_updated.zip" file from https://drive.google.com/drive/folders/1hsp2PlXAgcQ0pbx_vvPKHZcj_Am3rWx4 which appears to be the version of the dataset that the benchmark results reported here https://sustainlab-group.github.io/sustainbench/leaderboard/#crop-yield-prediction are based off of.
@chrisyeh96 in case you are interested!

Updates to SustainBenchCropYield dataset

---

torchgeo/trainers/classification.py
torchgeo/trainers/segmentation.py

Torchmetrics automatically applies the argmax on logits already if the datatype is float (so the logits) for the Classification Metrics https://lightning.ai/docs/torchmetrics/stable/classification/accuracy.html#multiclassaccuracy.
However, some metrics like [Calibration Error](https://lightning.ai/docs/torchmetrics/stable/classification/calibration_error.html#multiclasscalibrationerror) expect the logits. So in order to overwrite the configuration of metrics without having to change the train, val , test steps, this PR removes the argmax computation.

Remov Argmax Computation for torchmetrics in Classification and Segmentation

---

tests/transforms/test_transforms.py
torchgeo/transforms/transforms.py

When using the `_RandomNCrop` transform during training as an augmentation we need to be able to perform evaluation on the val and test sets on non overlapping patches of the same crop size.
While kornia.contrib contains an `ExtractPatches` transform, it unfortunately is not an augmentation therefore it a) doesn't work on masks in `K.AugmentationSequential` and b) has no option to combine the resulting patch dimension back into the batch dimensions for inference e.g. `b p c h w -> (b p) c h w` which breaks any downstream processing after the augmentation.
This PR adds the `_ExtractPatches` transform which can be used in the `test_aug` and `val_aug` augmentations in datamodules for evaluation on patches of images which aren't geotiffs (jpg, png, etc.), e.g. LEVIR-CD. 
Example:
```python …
```

ExtractPatches augmentation

---

.pre-commit-config.yaml

Type ignores added in 135f564837655ebf0146325e973d9336a998073e were not reflected in the pre-commit environment since `scikit-image` was not declared a dependency. This caused the `mypy` hook to fail with the following message:
```
pyupgrade................................................................Passed
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
pydocstyle...............................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1
torchgeo/datasets/vhr10.py:476: error: Unused "type: …
```

Fix for pre-commit

---

experiments/torchgeo/benchmark.py
tests/data/vhr10/data.py
torchgeo/losses/qr.py

Discovered some files that were missing a license header.
The command I used to find these was:
```console
> grep -RL --include '*.py' --include '*.sh' '^# Copyright (c) Microsoft Corporation' .
```
Not sure if there is an easy way to add a test for this, or whether or not it's worth testing in CI.

Ensure that all files have the license header at the top

---

pyproject.toml

Previously, all warnings were cast to errors when running pytest. This helped uncover the use of deprecated features, allowing us to stay on top of deprecations and ensure support for future versions of dependencies.
However, this also meant that minor platform-specific or version-specific warning messages would cause pytest to fail. Although it's maintainable in CI, it's impossible to support all the platforms and versions our developers are using.
This PR disables the casting of warning messages to errors. We'll need to be careful to make sure the release branch is relatively warning-free before making a release, but this will make life much easier for our developers.
@yichiac

pytest: don't cast warnings to errors

---

README.md

Package list was moved to a standalone website.

Fix Spack link in README

---

.github/labeler.yml

Files like README.md and CONTRIBUTING.md should also be considered documentation when adding PR labels.

Labeler: additional doc locations

---

.readthedocs.yaml

At the moment, Read the Docs is using the latest version of all non-documentation dependencies, meaning that an incompatible version of lightly is installed, and CI is failing for all PRs. We should always use the stable tested dependency versions managed by dependabot. This also helps ensure that the docs for future releases build into the distant future, not just at time of release.

RtD: use stable dependency versions

---

pyproject.toml

Fixes #1824
Hopefully smp will bump timm or lightly will check the timm version before use. Then we can unpin lightly.

lightly v1.4.26 is incompatible with smp

---

torchgeo/datasets/cdl.py

The USDA releases CDL data every year in January of the following year.

CDL: add 2023 checksum

---

.github/workflows/coverage.yaml
.github/workflows/tests.yaml

Solution for https://github.com/codecov/feedback/issues/126
Alternative to https://github.com/microsoft/torchgeo/pull/1845
The GitHub API has a strict rate limit. For PRs originating from https://github.com/microsoft/torchgeo, we use our own upload token. However, PRs originating from forks do not have access to repository secrets, and must instead use the same generic Codecov token as every other repository. The popularity of Codecov means that this generic token frequently exceeds the rate limit, resulting in the type of intermittent errors reported in https://github.com/codecov/codecov-action/issues/903. This error is usually tolerable since most of our test coverage is redundant, but the minimum tests hit a different code path. If the minimum tests encounter this issue, the total …

Solution for codecov rate limits

---

.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml
.github/workflows/tutorials.yaml
.readthedocs.yaml
experiments/torchgeo/run_resisc45_experiments.py
experiments/torchgeo/run_so2sat_experiments.py
experiments/torchgeo/run_so2sat_seed_experiments.py
pyproject.toml

Now that PyTorch 2.2 is out, which adds Python 3.12 support, we should see how many of our other dependencies support Python 3.12 and make sure TorchGeo supports it as well. This PR adds Python 3.12 to our unit tests.

Test Python 3.12

---

docs/api/landsat_pretrained_weights.csv
docs/api/naip_pretrained_weights.csv
docs/api/sentinel1_pretrained_weights.csv
docs/api/sentinel2_pretrained_weights.csv
torchgeo/models/swin.py
torchgeo/transforms/transforms.py

Documentation, satellite-specific transforms, and weights for additional Satlas single-image RGB & multispectral Swin-v2 models. Tests pass.
Few things:
- Renamed the existing model weights to include "SI", for single-image input. torchgeo doesn't support multi-image input yet, but there are multi-image Satlas models so hopefully someday those could be included.
- There are a couple custom transforms, for Landsat and multispectral Sentinel-2. Maybe there's a cleaner way to do this?

Additional Satlas pretrained models

---

README.md

Not sure why we didn't already have a link to this. I just rewatched it and it's still largely up to date.
Also changed our paper link to the arXiv version, which is easier to read for free. We still suggest citing the ACM version though.
@robmarkcole

README: add podcast episode

---

torchgeo/datasets/nccm.py

We weren't properly extracting the timestamp from the filename, we were just using the default `0` and `sys.maxsize`.
```console
> python3 -c 'from torchgeo.datasets import NCCM; print(NCCM("tests/data/nccm"))'
NCCM Dataset
type: GeoDataset
bbox: BoundingBox(minx=115.483402043364, maxx=115.48627665227318, miny=53.528522711204424, maxy=53.531397320113605, mint=0.0, maxt=9.223372036854776e+18)
size: 3
```
```console
> python3 -c 'from torchgeo.datasets import NCCM; print(NCCM("tests/data/nccm"))'
NCCM Dataset
type: GeoDataset
bbox: BoundingBox(minx=115.483402043364, maxx=115.48627665227318, miny=53.528522711204424, maxy=53.531397320113605, mint=1483225200.0, maxt=1577833199.999999)
size: 3
```
@shreyakannan1205 @yichiac

NCCM: fix timestamp extraction

---

tests/conf/chesapeake_cvpr_5.yaml
tests/conf/chesapeake_cvpr_7.yaml
tests/trainers/test_segmentation.py
torchgeo/trainers/base.py
torchgeo/trainers/segmentation.py

Correct behavior of ignore_index for JaccardLoss

---

torchgeo/samplers/single.py

Not sure how no one noticed this bug in the past 2 years...
#755 made `length` optional for all samplers. We provided a default value of None for RandomBatchGeoSampler, but not RandomGeoSampler. This PR fixes it so the optional length is _actually_ optional.

RandomGeoSampler: optional length is optional

---

torchgeo/datasets/xview.py

This is the only other place I found where we're using a set. @RitwikGupta maybe you can confirm that dataset order is not deterministic (even with setting a random seed) and confirm that this fixes it?

xView2: deterministic dataset order

---

README.md

Update VHR-10 snippet in README
Closes #1686

Update VHR-10 snippet

---

torchgeo/datasets/chabud.py
torchgeo/datasets/eurosat.py
torchgeo/datasets/l7irish.py
torchgeo/datasets/l8biome.py
torchgeo/datasets/mapinwild.py
torchgeo/datasets/skippd.py
torchgeo/datasets/ssl4eo.py
torchgeo/datasets/ssl4eo_benchmark.py
torchgeo/datasets/ucmerced.py
torchgeo/datasets/usavars.py
torchgeo/models/resnet.py
torchgeo/models/swin.py
torchgeo/models/vit.py

See https://discuss.huggingface.co/t/permalink-for-repositories/42691 for motivation.
Replacing huggingface.co with hf.co is entirely optional, just wanted to make the URL a little shorter.
Tested the model downloads with:
```console
> pytest -m slow tests/models/
```
Didn't test the dataset downloads.

HuggingFace: use stable download URLs

---

torchgeo/datasets/bigearthnet.py

Same as #1916 but for other git repos. We already do this for all GitHub repos.

GitLab: use stable download URLs

---

torchgeo/trainers/classification.py
torchgeo/trainers/detection.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py

Expanded description of averaging reduction method for Segmentation metrics. Let me know if you'd like me to change anything, or if I should add the details on macro accuracy. 
Closes #1874

Document default trainer metrics

---

pyproject.toml
torchgeo/trainers/detection.py

Just following the instructions from the error message:
```
tests/trainers/test_detection.py::TestObjectDetectionTask::test_trainer[True-faster-rcnn-nasa_marine_debris]
lib/python3.11/site-packages/lightning/pytorch/utilities/data.py:77: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 1. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
```

ObjectDetectionTask: explicit batch size

---

docs/conf.py
torchgeo/trainers/classification.py
torchgeo/trainers/detection.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py

Closes #1923 
We are nowhere near the limit of how much detail we could have. We can always start adding mathematical equations.
Alternative: why don't we just list the metrics and link to the torchmetrics docs? If a metric isn't properly explained, we can always improve the torchmetrics docs.
@robmarkcole @jdilger

Docs: fix trainer metric definitions

---

pyproject.toml

These are new warnings introduced in Python 3.12.
* docstring_parser: this has already been fixed on master, although we haven't seen a new release in a long time
* tarfile: this is just documenting a change in default behavior, nothing needs to be done here

pytest: silence Python 3.12 warnings

---

tests/trainers/test_utils.py

This was fun. Depending on the order in which these two tests are run, a second warning will be raised because the hack to fc or conv1 remained in effect. If either test was run on its own, there would be no warning. Proper solution is to monkeypatch instead of editing the original object.

load_state_dict: monkeypatch during testing

---

.github/dependabot.yml

We won't be able to use newer versions of codecov-action until they figure out how to use it for open-source repos. Even v3 doesn't really work due to GitHub's rate limit. We may want to consider looking for alternate coverage hosting services.

Dependabot: ignore codecov-action updates

---

torchgeo/trainers/byol.py
torchgeo/trainers/classification.py
torchgeo/trainers/moco.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py
torchgeo/trainers/simclr.py

Follow-up to #1928. After we squashed those warning messages, new ones popped up in other trainers.
I think I better understand the issue now. The logger would like to know the batch size. Normally, it infers this from the output of the data loader. However, we output a dictionary instead of a list of tensors, so it doesn't know how to infer this. The solution is to explicitly tell it what our batch size is.

BaseTask: explicitly pass batch size to logger

---

LICENSE

No one knows why the license is indented, and it usually isn't, so why not remove the indentation?
https://github.com/microsoft/repo-templates/issues/18

LICENSE: Remove indentation

---

docs/api/datamodules.rst
tests/conf/agrifieldnet.yaml
tests/trainers/test_segmentation.py
torchgeo/datamodules/__init__.py
torchgeo/datamodules/agrifieldnet.py

This PR adds the AgriFieldNet datamodule. The training uses satellite images included in the original dataset. We can experiment more with the Sentinel-2 raw scenes.

Add AgriFieldNet datamodule

---

.github/labeler.yml
.readthedocs.yaml

Attempting to resolve the following warning message:
```
/home/docs/checkouts/readthedocs.org/user_builds/torchgeo/envs/1903/lib/python3.12/site-packages/nbsphinx/__init__.py:1058: RuntimeWarning: You are using an unsupported version of pandoc (2.9.2.1).
Your version must be at least (2.14.2) but less than (4.0.0).
Refer to https://pandoc.org/installing.html.
Continuing with doubts...
nbconvert.utils.pandoc.check_pandoc_version()
```

RtD: use latest Ubuntu

---

docs/_static/table-scroll.css
docs/conf.py

Also submitted upstream to https://github.com/pytorch/pytorch_sphinx_theme/pull/192, can be removed once that PR is accepted.
https://torchgeo.readthedocs.io/en/latest/api/models.html#sensor-agnostic
https://torchgeo--1958.org.readthedocs.build/en/1958/api/models.html#sensor-agnostic

Docs: allow horizontal scrolling of wide tables

---

pyproject.toml
requirements/min-reqs.old
torchgeo/models/dofa.py
torchgeo/models/resnet.py
torchgeo/models/swin.py
torchgeo/models/vit.py

Switch to kornia's `AugmentationSequential` in `models` submodule

models: Switch to kornia AugmentationSequential

---

docs/tutorials/custom_raster_dataset.ipynb

Spotted a tiny typo in `custom_raster_dataset.ipynb` --my inner nitpicker couldn't resist pointing it out.

Minor typo in notebook

---

torchgeo/datasets/fire_risk.py

The FireRisk dataset has been rehosted to HuggingFace. This PR updates the download url
Fixes #1996

FireRisk HuggingFace Port

---

torchgeo/datamodules/geo.py

We have a `.plot(...)` method in our `BaseDataModule` that routes plot requests from the trainers through to the dataset object's `.plot(...)` method. This currently only works if `trainer.dataset` or `trainer.val_dataset` has a plot method. However, when you call `torch.utils.data.random_split` to get a train/val split, your dataset objects are `Subsets` which don't have a plot method.

Fix plotting in datamodules when dataset is a Subset

---

.pre-commit-config.yaml

Otherwise it complains about an unused type ignore since https://github.com/microsoft/torchgeo/pull/1617

pre-commit: newer skimage is required

---

tests/conf/skippd.yaml
tests/datamodules/test_utils.py
torchgeo/datamodules/deepglobelandcover.py
torchgeo/datamodules/gid15.py
torchgeo/datamodules/levircd.py
torchgeo/datamodules/nasa_marine_debris.py
torchgeo/datamodules/oscd.py
torchgeo/datamodules/potsdam.py
torchgeo/datamodules/skippd.py
torchgeo/datamodules/spacenet.py
torchgeo/datamodules/utils.py
torchgeo/datamodules/vaihingen.py
torchgeo/datamodules/vhr10.py
torchgeo/datamodules/xview.py

This function was added as a wrapper around `torch.utils.data.random_split` with support for percentages. However, this feature was added upstream, and the minimum supported version of PyTorch now supports it. This wrapper can now be removed.
There are no backwards incompatible changes since this function was never documented.

Remove torchgeo.datamodules.dataset_split

---

.github/dependabot.yml
.github/labeler.yml

Discovered a few cool new features:
Additionally, I removed the ignore for codecov-action. It's broken anyway, so updates can't make it any worse. Right?

Dependabot: update devcontainer, group torch

---

.git-blame-ignore-revs

This PR adds a `.git-blame-ignore-revs` file. What does this magical file do? It ignores certain commits (revisions) when viewing file in `git blame` and the GitHub blame view: 
* https://github.blog/changelog/2022-03-24-ignore-commits-in-the-blame-view-beta/
* https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view
* https://git-scm.com/docs/git-blame/en
All of these commits change a large number of files, but only involve cosmetic changes, and should be ignored when looking for the origin of each line.

git blame: ignore revs

---

torchgeo/datasets/splits.py
torchgeo/datasets/utils.py
torchgeo/models/dofa.py
torchgeo/models/resnet.py
torchgeo/models/swin.py
torchgeo/models/vit.py

In TorchGeo, we use `__all__` to prevent "unused import" errors from ruff (formerly flake8). These are only needed in `__init__.py` files to support import aliasing. However, this has led to the proliferation of `__all__` in a few other places. This PR cleans those up.

Avoid use of __all__

---

hubconf.py
tests/models/test_api.py
torchgeo/models/api.py
torchgeo/models/dofa.py

We forgot to add support for DOFA and Swin ViT to `torch.hub`.

torch.hub: add support for DOFA and Swin models

---

tests/datasets/test_l7irish.py
torchgeo/datasets/l7irish.py

Converts L7 Irish to an IntersectionDataset following the design proposed in #1972.
This is needed for #2015 so that images and masks can independently control their resampling algorithm.
~Only remaining bug is that the length of the dataset jumped from 206 to 438, which implies that some images in the dataset overlap.~
Will do the same thing to L8 Biome after this is merged.
@yichiac

L7 Irish: convert to IntersectionDataset

---

torchgeo/datasets/geo.py

Many of our GeoDatasets use `self.files` to check if the dataset has already been downloaded. However, `self.files` warns if this is not the case. This results in situations like:
```pycon
>>> from torchgeo.datasets import L7Irish, L8Biome
>>> L7Irish('data/l7irish', download=True, checksum=True)
/Users/Adam/torchgeo/torchgeo/datasets/geo.py:313: UserWarning: Could not find any relevant files for provided path 'data/l7irish'. Path was ignored.
warnings.warn(
Downloading https://cdn-lfs.huggingface.co/repos/0e/db/0edbfb877a18f0d038f1adf0a0a8f2cbc1cf4d3ac25ad56be221421cb1667b22/9b025debb20791cd3279cbc56f39dcd42fa7f20f172608a750e06b31c153457e?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27austral.tar.gz%3B+filename%3D%22austral.tar.gz%22%3B&response-content-type=application …
```

GeoDataset: don't warn about missing files for downloadable datasets

---

tests/datasets/test_l8biome.py
torchgeo/datasets/l8biome.py

Converts L8 Biome to an IntersectionDataset following the design proposed in #1972.
Same as #2034.
This is needed for #2015 so that images and masks can independently control their resampling algorithm.

L8 Biome: convert to IntersectionDataset

---

tests/datasets/azcopy
tests/datasets/conftest.py
tests/datasets/test_errors.py
tests/datasets/test_utils.py
torchgeo/datasets/errors.py
torchgeo/datasets/utils.py

Alternative to #2043 
#2043 is difficult to test because it requires `azcopy` to _not_ be installed, but it seems like it is installed on the GitHub Actions runners.
This PR goes in a different direction by adding a generic `which` function that returns an `Executable` for interacting with _any_ command-line program, not just `azcopy`. This is a watered-down version of the same idea used by [Spack](https://github.com/spack/spack/blob/develop/lib/spack/spack/util/executable.py), and can be used as follows:
```python
from torchgeo.datasets.utils import which
azcopy = which("azcopy")
azcopy("sync", "https://radiantearth.blob.core.windows.net/mlhub/nasa-tropical-storm-challenge", ".", "--recursive=true")
```
Prerequisite for #1830 and #2068
Closes #1887
Closes #1915
Closes #2043

Datasets: add CLI support

---

tests/datasets/test_agb_live_woody_density.py
tests/datasets/test_astergdem.py
tests/datasets/test_cbf.py
tests/datasets/test_cdl.py
tests/datasets/test_chesapeake.py
tests/datasets/test_cloud_cover.py
tests/datasets/test_cms_mangrove_canopy.py
tests/datasets/test_enviroatlas.py
tests/datasets/test_esri2020.py
tests/datasets/test_eudem.py
tests/datasets/test_eurocrops.py
tests/datasets/test_iobench.py
tests/datasets/test_l7irish.py
tests/datasets/test_l8biome.py
tests/datasets/test_landsat.py
tests/datasets/test_naip.py
tests/datasets/test_nccm.py
tests/datasets/test_nlcd.py
tests/datasets/test_openbuildings.py
tests/datasets/test_sentinel.py
tests/datasets/test_south_america_soybean.py

Many of our datasets lacked any method to test the length of the dataset. Adding these tests uncovered several issues (#2086, #2087, #2089). This PR adds these tests to the remaining datasets that did not contain any bugs.

Datasets: test length

---

tests/datasets/test_globbiomass.py
torchgeo/datasets/geo.py
torchgeo/datasets/globbiomass.py

This PR fixes the following bugs:
I also improved the documentation to include definitions and units of AGB and GSV.
I didn't do these in this PR, but some suggestions for future contributions to this dataset:

GlobBiomass: several bug fixes

---

README.md
torchgeo/datasets/vhr10.py

Fix plotting using percentiles
Note: I have uploaded the dataset at https://huggingface.co/datasets/satellite-image-deep-learning/VHR-10 - can transfer to torchgeo org if you want to use it here

Update VHR-10 dataset plotting

---

pyproject.toml
requirements/min-reqs.old

kornia v0.7.3 contains the following fixes necessary for supporting instance segmentation masks and removing our `AugmentationSequential`.
- kornia/kornia#2846
- kornia/kornia#2856
- kornia/kornia#2873
- kornia/kornia#2882

Bump kornia min version

---

tests/transforms/test_color.py
tests/transforms/test_indices.py

Switch to kornia's `AugmentationSequential` in `transforms` submodule
Closes #2002

transforms: Switch to kornia AugmentationSequential

---

.github/dependabot.yml
pyproject.toml

Until https://github.com/Lightning-AI/pytorch-lightning/issues/19977 is resolved, let's prevent users from installing broken TorchGeo dependencies.
@CarlosGomes98

Lightning 2.3+ contains known bugs with YAML parsing

---

pyproject.toml
torchgeo/datasets/biomassters.py
torchgeo/datasets/dfc2022.py
torchgeo/datasets/eurocrops.py

Uses ruff to upgrade TorchGeo to support NumPy 2.
We can't actually test NumPy 2 support because torchvision and lightly don't yet support NumPy 2. #2123 is stalled waiting for them to make new releases.

NumPy 2 support

---

tests/data/README.md

While generating fake rasterdata I noticed a small error in the readme that gave me an `AttributeError: 'Profile' object has no attribute 'indexes'`.

Update to readMe of generating testdata

---

docs/_static/badge-height.css
docs/_static/button-width.css
docs/conf.py
docs/tutorials/prolog.rst.jinja

Adds a new button to our tutorials to open them in the new Lightning Studio platform.
Based on https://lightning.ai/badge.
Still need to test, but I think this code organization is more clear in my mind.

Tutorials: add Open in Studio badge

---

docs/tutorials/custom_raster_dataset.ipynb

The dataset has to be downloaded before you can call `super().__init__()`.

Custom raster datasets tutorial: download before super

---

tests/datasets/test_geo.py
torchgeo/datasets/geo.py

@erob-archim can you see if this fixes #2190?

RasterDataset: calculate res after changing crs

---

tests/data/western_usa_live_fuel_moisture/data.py
tests/datamodules/test_geo.py
torchgeo/datamodules/geo.py
torchgeo/datasets/agrifieldnet.py
torchgeo/datasets/chesapeake.py
torchgeo/datasets/eddmaps.py
torchgeo/datasets/enviroatlas.py
torchgeo/datasets/gbif.py
torchgeo/datasets/geo.py
torchgeo/datasets/globbiomass.py
torchgeo/datasets/inaturalist.py
torchgeo/datasets/landcoverai.py
torchgeo/datasets/openbuildings.py
torchgeo/datasets/south_africa_crop_type.py

'bbox' in kornia augmentations is used to identify bounding boxes of instances in an image. However, in GeoDatasets, bbox refers to the geographic bounds of the data. This PR aims to make these distinct by renaming 'bbox' in GeoDatasets to 'geo_bbox'
`bounds` could also be another option.

Rename bbox -> bounds

---

pyproject.toml

Let's see if we can resolve all the warnings in CI from Python 3.12/Torch 2.4.

Testing: suppress warnings

---

tests/conftest.py
tests/models/test_dofa.py
tests/models/test_resnet.py
tests/models/test_swin.py
tests/models/test_vit.py
tests/trainers/test_byol.py
tests/trainers/test_classification.py
tests/trainers/test_moco.py
tests/trainers/test_regression.py
tests/trainers/test_segmentation.py
tests/trainers/test_simclr.py

We don't need to define a `load` function in every single test file, we can create a shared fixture in `conftest.py`.

Testing: shared load_state_dict_from_url monkeypatch

---

tests/datasets/test_geo.py
torchgeo/datasets/geo.py

If the user passes a list of files including all bands, ignore everything other than the primary band so that the file doesn't end up in the index multiple times.
The dataset length matches what you would expect, and each bounding box is not sampled multiple times. This is especially important when using a dataset splitter to avoid the same image ending up in both train and test.
Requires the users to ensure that the `bands` parameter includes the bands in `paths`.
Fixes #2221 
@sfalkena @adriantre can you review?

GeoDataset: ignore other bands for separate files

---

pyproject.toml
torchgeo/datasets/utils.py
torchgeo/transforms/transforms.py

Adds additional checks like `warn_unreachable` that revealed new bugs. And fixes those bugs!
I also played around with generics like:
```python
from typing import TypeVar
K = TypeVar('K')
V = TypeVar('V')
```
but ran into too many issues and gave up. Maybe another day.

mypy: even more strict

---

tests/datasets/test_utils.py
torchgeo/datasets/utils.py

A simple logic to replace %% with a placeholder string in _disambiguate_timestamp_ before parsing the date string and reverting it back afterward

RasterDataset: support date_str containing % character

---

pyproject.toml

We should consider adding https://coverage.readthedocs.io/en/latest/branch.html in the future. At the moment, we only have 98% coverage using this setting.

Coverage: update to modern config flag

---

docs/tutorials/pretrained_weights.ipynb
docs/user/contributing.rst
docs/user/installation.rst
pyproject.toml
torchgeo/__init__.py
torchgeo/datasets/advance.py
torchgeo/datasets/cdl.py
torchgeo/datasets/chesapeake.py
torchgeo/datasets/deepglobelandcover.py
torchgeo/datasets/dfc2022.py
torchgeo/datasets/enviroatlas.py
torchgeo/datasets/eudem.py
torchgeo/datasets/idtrees.py
torchgeo/datasets/inaturalist.py
torchgeo/datasets/loveda.py
torchgeo/datasets/openbuildings.py
torchgeo/datasets/pastis.py
torchgeo/datasets/reforestree.py
torchgeo/datasets/seco.py
torchgeo/datasets/sentinel.py
torchgeo/models/farseg.py
torchgeo/models/resnet.py
torchgeo/models/vit.py
torchgeo/trainers/byol.py
torchgeo/transforms/indices.py

These bugs can be found using:
```console
> cd docs
> make linkcheck
```
On macOS, I need to use:
```console
> sphinx-build -M linkcheck . _build -W -j auto --keep-going
```
to avoid SIP.

Docs: fix broken links and redirects

---

docs/api/weights/agnostic.csv
torchgeo/models/dofa.py

@ando-shah discovered a minor bug (1-line) in DOFA with major consequences (performance is sensitive to band order). @ShadowXZT fixed this and is currently retraining the model. I'll update the model weights once this is done and hopefully we can sneak this in to the 0.6.0 release.

DOFA: fix bug in patch embedding

---

.github/release.yml
docs/conf.py
docs/user/contributing.rst
pyproject.toml
tests/conftest.py
torchgeo/__init__.py
torchgeo/datamodules/digital_typhoon.py
torchgeo/datamodules/geonrw.py
torchgeo/datasets/digital_typhoon.py
torchgeo/datasets/eurocrops.py
torchgeo/datasets/levircd.py
torchgeo/trainers/byol.py
torchgeo/trainers/segmentation.py

https://github.com/microsoft/torchgeo/milestone/16
#2078

0.6.0 release

---

tests/datasets/test_geo.py
torchgeo/datasets/geo.py

Currently, if a user passes in both str and pathlib.Path paths, GeoDataset crashes:
```
>       return sorted(files)
E       TypeError: '<' not supported between instances of 'PosixPath' and 'str'
```
The easiest solution is to convert all values to the same type for easy comparison. This also prevents duplicates, since:
```pycon
>>> import os
>>> import pathlib
>>> x = "foo/bar"
>>> y = pathlib.Path("foo/bar")
>>> x == y
False
```
FYI @pioneerHitesh @adriantre

GeoDataset: allow a mix of str and pathlib paths

---

.prettierignore

By default, prettier ignores everything in the root `.gitignore`. However, many of our tools create their own hidden directories with a `.gitignore` inside that prettier does not recognize. This PR adds those to the ignore, speeding up writing (`.ruff_cache` in particular was slowing things down).
@Domejko

Prettier: ignore cache directories

---

pyproject.toml

We are now testing numpy 2 in CI, so the NPY201 compatibility check by ruff is no longer needed.

Ruff: remove NPY tests

---

tests/datasets/test_geo.py
torchgeo/datasets/agb_live_woody_density.py
torchgeo/datasets/agrifieldnet.py
torchgeo/datasets/cbf.py
torchgeo/datasets/cdl.py
torchgeo/datasets/chesapeake.py
torchgeo/datasets/cms_mangrove_canopy.py
torchgeo/datasets/esri2020.py
torchgeo/datasets/eudem.py
torchgeo/datasets/eurocrops.py
torchgeo/datasets/geo.py
torchgeo/datasets/globbiomass.py
torchgeo/datasets/l7irish.py
torchgeo/datasets/l8biome.py
torchgeo/datasets/landcoverai.py
torchgeo/datasets/nlcd.py
torchgeo/datasets/openbuildings.py
torchgeo/datasets/south_africa_crop_type.py
torchgeo/datasets/south_america_soybean.py
torchgeo/datasets/utils.py

As of #2173, all TorchGeo datasets now support both `str` and `pathlib.Path` paths. However, `pathlib.Path` is actually a subclass of `os.PathLike`, and [PEP 519](https://peps.python.org/pep-0519/#provide-specific-type-hinting-support) says to use:
```
typing.Union[str, bytes, os.PathLike]
```
to type hint all paths (we skipped `bytes` because it was a nightmare). This PR expands our support to all of `os.PathLike` (although I don't know any subclasses other than `pathlib.Path`).
@pioneerHitesh was there a reason we chose `pathlib.Path` instead of `os.PathLike`?

Datasets: support os.PathLike

---

.github/dependabot.yml
requirements/package.json

Previously, dependabot would update both `package.json` (equivalent of `pyproject.toml`) and `package-lock.json` (equivalent of `requirements/style.txt`). Now it will only update the latter.
@Domejko

Dependabot: only update npm lockfile

---

torchgeo/datamodules/geo.py

PyTorch Lightning issues a warning to suggest this. I didn't notice any speedup in data loading, but it did make Lightning quieter.

DataModules: use persistent workers for parallel data loading

---

pyproject.toml

PyTorch's `__array__` implementation is not fully compatible with NumPy 2's `__array__` implementation, leading to some warning messages. I reported this issue to PyTorch. Let's let them decide the right way to handle this.
* https://github.com/pytorch/pytorch/issues/136264

pytest: silence numpy 2 warnings

---

docs/user/contributing.rst

`docs/api/*_datasets.csv` were moved to `docs/api/datasets/`. Everything else is just grammar changes.

Contributing: update dataset CSV file location

---

.github/workflows/release.yaml
.github/workflows/tutorials.yaml

In our tutorial notebooks we have an initial cell does a `%pip install torchgeo` along with any optional dependencies for that specific notebook (currently planetary-computer and pystac for downloading data). One notebook uses tensorboard so `pip install`s that as well. This PR adds tensorboard to the CI setup so we don't waste valuable time (time that we could spend running random data through random models to make sure dimensions align 😃) on downloading tensorboard at test time.

Adding tensorboard to CI

---

tests/models/test_api.py
torchgeo/models/api.py

Removing use of eval.
~@nilsleh -- do you remember what the use case for eval was? If not, I say we replace all instances of `get_weight` with `get_model_weights` and remove `get_weight`.~ Nevermind, I understand it now.
`get_weight(...)` allows a user to pass a string "ResNet18_Weights.LANDSAT_ETM_SR_MOCO" and get back the object `ResNet18_Weights.LANDSAT_ETM_SR_MOCO` WeightEnum. Previously we did this with `eval("ResNet18_Weights.LANDSAT_ETM_SR_MOCO")` which is _bad_. This proposed fix simply iterates through all available WeightEnums to look for matches and has the benefit of raising an error that makes sense if there is no match (vs. the `eval(...)` which would do whatever).

Removing eval in model weight API

---

torchgeo/trainers/base.py
torchgeo/trainers/byol.py
torchgeo/trainers/classification.py
torchgeo/trainers/detection.py
torchgeo/trainers/moco.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py
torchgeo/trainers/simclr.py

Alternative to #2314. @calebrob6 can you see if this also fixes your issue?
I think this makes more sense, as `ignore` is more of a class attribute than an instance parameter. It also makes it possible to add subclasses with additional ignores. Downside is that it's technically backwards incompatible and will have to wait until 0.7.0.

BaseTask: fix load_from_checkpoint, ignore 'ignore'

---

.github/workflows/tests.yaml
tests/conftest.py

The default matplotlib backend is interactive. In CI, this results in the tests hanging. Locally, this can result in the terminal losing focus. In CI, we worked around this by setting the `MPLBACKEND` environment variable. However, this doesn't solve the problem locally. This PR uses `matplotlib.use` instead, and works both locally and in CI.
Reference: https://matplotlib.org/stable/users/explain/figure/backends.html

Tests: set matplotlib backend locally too

---

docs/api/datasets/geo_datasets.csv

I'm seeing a lot of conflicting reports here:
* [USDA, 2013](https://www.fsa.usda.gov/Internet/FSA_File/naip_info_sheet_2013.pdf): "NAIP imagery has a 1-meter ground sample distance (GSD). Beginning with the 2011 NAIP season, ½-meter GSD imagery is an option... In earlier years of NAIP, some states were flown at a 2-meter GSD"
* [USGS, 2018](https://www.usgs.gov/centers/eros/science/usgs-eros-archive-aerial-photography-national-agriculture-imagery-program-naip): "a resolution of 1-meter ground sample distance (GSD) ... from 2003–2017... In 2018, the ground resolution standard changed to .6 meter with the option for .3 meter data was added for consideration..."
* [ESRI, 2020](https://www.esri.com/arcgis-blog/products/arcgis-living-atlas/imagery/fast-and-simple-naip-imagery/): "The spatial …

NAIP: update resolution

---

pyproject.toml

Rasterio 1.4 no longer supports merging WarpedVRT objects. Based on https://github.com/rasterio/rasterio/issues/3196, it sounds like this wasn't directly intentional, but also like this also isn't exactly recommended. This may be changed in a future version of rasterio, but it won't be in 1.4.1. Let's pin rasterio for now and brainstorm ways of supporting rasterio 1.4 when we have more time.
Closes #2321

TorchGeo is not yet compatible with rasterio 1.4

---

.github/workflows/deploy.yaml

Closes #2269
We _could_ test this by enabling it on every push and releasing to testpypi instead of pypi, but I'm hoping it Just Works™.

Set up continuous deployment for PyPI releases

---

torchgeo/models/resnet.py
torchgeo/models/scale_mae.py
torchgeo/models/vit.py

This PR introduces consistent `bands` metadata across `vit.py` and `resnet.py` weight classes to enhance usability and ensure alignment with existing metadata standards in the project.
- Added `bands` metadata for Vision Transformer (ViT) weight classes.
- Updated `vit.py` to import `_satlas_bands`, `_satlas_sentinel2_bands`, and `_satlas_landsat_bands` from `swin.py` for consistent band definitions.
- Applied correct band metadata for each ViT weight class, supporting Landsat and Sentinel datasets, ensuring metadata aligns with project standards.
- Added `bands` metadata for ResNet weight classes, providing consistent metadata across ResNet weights.
- Updated `resnet.py` to import `_satlas_bands`, `_satlas_sentinel2_bands`, and `_satlas_landsat_bands` from `swin.py`.
- Updated metadata …

Add Consistent `bands` Metadata to Vision Transformer and ResNet Weights

---

torchgeo/datasets/__init__.py

`Chesapeake7` and `Chesapeake13` are not found in the datasets. They should be removed.

Remove Chesapeake7 and Chesapeake13

---

torchgeo/datasets/forestdamage.py
torchgeo/datasets/millionaid.py

The dangers of copy-n-paste...
Neither of these methods return anything, but the docstring was copied from ADVANCE and no one noticed.

Million-AID, ForestDamage: fix _verify docstring

---

.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml
.github/workflows/tutorials.yaml

```
/opt/hostedtoolcache/Python/3.12.7/x64-3b491464e61eae98f153313411700ba1d39523afb48d65a0fdbf87169a2fec47-0a9e6061bf3458e835d80bb55172c9774b8554394191affef6ca0e34adafd892-ed2c4866b3205f95957b20e49eb96607af97b6c1bba732783fcbe7fd9372df15
```
```
Linux-X64-Python-3.12.7-433dc1e38a445c7d575a66bbce5899ca3cfe8ded048b2f11c7c9304a919fd51c
```

CI: more human-readable cache names

---

docs/index.rst
docs/tutorials/pytorch.ipynb

The first of many tutorials introduced for #2418 
This tutorial is designed for remote sensing folks with little to no background in deep learning or PyTorch. It provides a foundation upon which all later tutorials will build.

Add Introduction to PyTorch tutorial

---

docs/tutorials/pretrained_weights.ipynb
docs/tutorials/transforms.ipynb

Update tutorial for transforms according to https://github.com/microsoft/torchgeo/issues/2418

Update tutorial for transforms and pretrained weights

---

docs/tutorials/geospatial.ipynb
docs/tutorials/pytorch.ipynb

`\mathcal{}` does not render correctly on Google Colab: https://github.com/googlecolab/colabtools/issues/3192
Let's just remove it so the tutorials are widely accessible.

Docs: remove mathcal

---

docs/tutorials/basic_usage.rst
docs/tutorials/cli.ipynb

Basically copied the docs from the README to a tutorial.

Add TorchGeo CLI tutorial

---

README.md

`console` is only for code prefixed with `$`, `sh` should be used elsewhere. Also, console code including `$` results in the Copy button also copying the `$`. Let's remove it to make it easier to copy-n-paste code examples.
https://github.com/microsoft/torchgeo
https://github.com/adamjstewart/torchgeo/tree/docs/readme-console

README: correct syntax highlighting for console code

---

.github/workflows/tests.yaml
.pre-commit-config.yaml
docs/conf.py
pyproject.toml
requirements/datasets.txt
requirements/min-reqs.old
tests/datasets/test_idtrees.py
torchgeo/datasets/idtrees.py

I don't think this feature (`IDTReeS.plot_las`) is widely used and it requires multiple dependencies (`pyvista`, `pyvista/setup-headless-display-action`) just to test. Visualization has always been orthogonal to TorchGeo's goals. We would like the bare minimum plotting capable in matplotlib. Users can always use PyVista themselves outside of TorchGeo.

IDTReeS: remove support for plotting lidar point cloud

---

torchgeo/datasets/satlas.py

Otherwise the CSV table hyperlink goes straight to the homepage.

SatlasPretrain: fix table hyperlink

---

torchgeo/datasets/etci2021.py

Well this was one of the weirder bugs I've encountered in CI. See if you can spot the difference:
```
/private/var/folders/2s/h6hvv9ps03xgz_krkkstvq_r0000gn/T/pytest-of-runner/pytest-0/test_getitem_train_0/train/bangladesh_20170314t115609/tiles/vh/bangladesh_20170314t115609_x-0_y-0_vh.png
/private/var/folders/2s/h6hvh9ps03xgz_krkkstvq_r0000gn/T/pytest-of-runner/pytest-0/test_getitem_train_0/train/bangladesh_20170314t115609/tiles/vh/bangladesh_20170314t115609_x-0_y-0_vh.png
```
No? The difference is that the first string contains a random hash which accidentally contains `vv`, and our dataset was replacing all occurrences of `vv` with `vh` to get the cross-polarization file path. This was causing the tests to fail only on macOS since the tmp path is different on each OS. This bug has been …

ETCI2021: fix file list when 'vv' in directory name

---

.github/workflows/tests.yaml
docs/user/contributing.rst
pyproject.toml

@calebrob6 does this fix the issue you reported? It works for me, but I'm not 100% sure it will always work for everyone. If you can figure out a way to break this I'll reach out to the pytest-cov developers because I really want this to work, especially as we increase the number of datasets.

Fix file-specific test coverage

---

torchgeo/datasets/mdas.py

Silences the following warning in CI:
```
tests/datasets/test_mdas.py: 40 warnings
/home/runner/work/torchgeo/torchgeo/torchgeo/datasets/mdas.py:359: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
cmap = ListedColormap([cm.get_cmap('tab20')(i) for i in range(20)])
```

MDAS: silence matplotlib deprecation warning

---

torchgeo/datasets/landsat.py

There is no SR_B6, this band is TOA-only.

Landsat 7: fix default bands

---

.devcontainer/devcontainer.json
.github/workflows/deploy.yaml
.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml
.github/workflows/tutorials.yaml
.readthedocs.yaml
pyproject.toml

Will drop 3.10 support in a separate PR.

CI: add Python 3.13 tests

---

.pre-commit-config.yaml
docs/api/transforms.rst
tests/datamodules/test_fair1m.py
tests/datasets/test_fair1m.py
tests/datasets/test_forestdamage.py
tests/datasets/test_idtrees.py
tests/datasets/test_nasa_marine_debris.py
tests/datasets/test_pastis.py
tests/datasets/test_reforestree.py
tests/datasets/test_vhr10.py
tests/datasets/test_zuericrop.py
tests/transforms/test_transforms.py
torchgeo/datamodules/fair1m.py
torchgeo/datamodules/nasa_marine_debris.py
torchgeo/datamodules/utils.py
torchgeo/datamodules/vhr10.py
torchgeo/datasets/fair1m.py
torchgeo/datasets/forestdamage.py
torchgeo/datasets/idtrees.py
torchgeo/datasets/nasa_marine_debris.py
torchgeo/datasets/pastis.py
torchgeo/datasets/reforestree.py
torchgeo/datasets/vhr10.py
torchgeo/datasets/zuericrop.py
torchgeo/trainers/detection.py
torchgeo/transforms/transforms.py

The next version of kornia (`0.7.3`) will contain 2 fixes (kornia/kornia#2846, kornia/kornia#2856) that will allow us to drop AugPipe and have detection only depend on kornia's `AugmentationSequential`.

Remove AugPipe

---

torchgeo/datasets/digital_typhoon.py

I must have updated the wrong md5sum when I first added the datasets, but these are the updated checksums, that I confirm I get when downloading from HF and also on the other machine, where I uploaded the dataset to HF from.

Wrong md5sum in digital typhoon

---

torchgeo/datasets/vhr10.py

Previously if split was not 'negative', unnormalized image was shown. Had accidently introduced this bug in #1978 
Before:
After:

VHR-10 plot fix

---

docs/api/datasets/non_geo_datasets.csv

We missed a column in #2520, see https://torchgeo.readthedocs.io/en/latest/api/datasets.html#non-geospatial-datasets

BRIGHT: document image size

---

docs/api/models.rst
tests/models/test_dofa.py
torchgeo/models/__init__.py
torchgeo/models/dofa.py

Fix the inconsistent patch size of DOFA huge model, specifically:
docs/api/models.rst:.. autofunction:: dofa_huge_patch16_224, changed to autofunction:: dofa_huge_patch14_224
tests/models/test_dofa.py: dofa_huge_patch16_224, changed to dofa_huge_patch14_224
tests/models/test_dofa.py: dofa_huge_patch16_224() changed to dofa_huge_patch14_224()
torchgeo/models/init.py: dofa_huge_patch16_224, changed to dofa_huge_patch14_224
torchgeo/models/init.py: 'dofa_huge_patch16_224', changed to dofa_huge_patch14_224
torchgeo/models/dofa.py: def dofa_huge_patch16_224(*args: Any, **kwargs: Any) -> DOFA: changed to dofa_huge_patch14_224(*args: Any, **kwargs: Any)
Closes #2618

fix inconsistent patch size in dofa huge model

---

tests/trainers/test_detection.py
torchgeo/trainers/detection.py
torchgeo/trainers/instance_segmentation.py

We don't yet have a non-RGB object detection dataset to test with, but I'm pretty sure this works. Needed to bump some deps and throw away some tests to get it to work.
Closes #1156

ObjectDetectionTask: support for non-RGB imagery (SAR, MSI, HSI)

---

.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml
.github/workflows/tutorials.yaml

The main branch is special, as all of our:
[![docs](https://readthedocs.org/projects/torchgeo/badge/?version=latest)](https://torchgeo.readthedocs.io/en/stable/)
[![style](https://github.com/microsoft/torchgeo/actions/workflows/style.yaml/badge.svg)](https://github.com/microsoft/torchgeo/actions/workflows/style.yaml)
[![tests](https://github.com/microsoft/torchgeo/actions/workflows/tests.yaml/badge.svg)](https://github.com/microsoft/torchgeo/actions/workflows/tests.yaml)
[![codecov](https://codecov.io/gh/microsoft/torchgeo/branch/main/graph/badge.svg?token=oa3Z3PMVOg)](https://codecov.io/gh/microsoft/torchgeo)
buttons display current test results and code coverage on main. We should not skip in-progress CI runs on the main branch just because a newer commit has been pushed. This will keep …

CI: do not cancel runs on main branch

---

torchgeo/datasets/geo.py

Curious how many datasets are missing a definition of `all_bands`.

RasterDataset: assert valid bands

---

tests/conf/digital_typhoon_id.yaml
tests/conf/digital_typhoon_time.yaml
tests/conf/io_preprocessed.yaml
tests/conf/io_raw.yaml

When following https://torchgeo.readthedocs.io/en/latest/user/contributing.html#i-o-benchmarking, the config files are supposed to download the data for you (hence `checksum: true`). At some point, this was removed (probably by me) to avoid our tests downloading data. This PR re-adds automatic downloads (and removes it from Digital Typhoon).

I/O Bench: automatically download data

---

tests/conftest.py
tests/models/conftest.py
tests/models/test_resnet.py
tests/models/test_vit.py
torchgeo/models/resnet.py
torchgeo/models/vit.py

Fix the AssertionError raised when pretrained ResNet/ViT models (from timm) were created with `features_only = True`.
ResNet18 and Swin models were not affected by the issue (Swin models are created with torchvision instead of timm).
Closes [#2640](https://github.com/microsoft/torchgeo/issues/2640).

Fix Pretrained ResNet/ViT not working when features_only=True

---

docs/tutorials/custom_segmentation_trainer.ipynb
docs/tutorials/customization.rst

Re-upped version of #1897
For review convenience, [here's a link to the notebook](https://github.com/microsoft/torchgeo/blob/tutorials/custom_segmentation/docs/tutorials/custom_segmentation_trainer.ipynb).

Custom semantic segmentation tutorial

---

.github/workflows/tests.yaml
tests/models/conftest.py
tests/models/test_copernicusfm.py
tests/models/test_croma.py
tests/models/test_dofa.py
tests/models/test_resnet.py
tests/models/test_scale_mae.py
tests/models/test_swin.py
tests/models/test_vit.py
torchgeo/models/resnet.py
torchgeo/models/vit.py

TorchGeo now has a whopping 93 builtin pre-trained model weights. These weights have become prohibitively expensive to test, resulting in a significant slowdown and intermittent test failures. This PR is designed to resolve this issue.
At the moment, we test all model weights roughly 6 times: with `features_only` True and False, and for weight-loading, bands, and transforms. This means we are instantiating and saving large models to disk (sometimes as large as ViT-H) $$93 \times 6 = 576$$ times per OS, per Python version, and per commit. This adds up very quickly:
```console
> pytest tests/models/
...
==== 666 passed, 93 deselected in 926.76s (0:15:26) ====
```
We apply the following changes to reduce the amount of testing:
The result is still 100% test coverage, with all weights still …

Models: fix features_only loading, avoid redundant weight tests

---

tests/conf/reforestree.yaml
tests/datamodules/test_levircd.py
tests/datamodules/test_oscd.py
torchgeo/datamodules/deepglobelandcover.py
torchgeo/datamodules/gid15.py
torchgeo/datamodules/inria.py
torchgeo/datamodules/levircd.py
torchgeo/datamodules/oscd.py
torchgeo/datamodules/potsdam.py
torchgeo/datamodules/reforestree.py
torchgeo/datamodules/vaihingen.py
torchgeo/transforms/transforms.py

This PR fixes https://github.com/microsoft/torchgeo/issues/2667 and refactors `_RandomNCrop` out of segmentation and change detection datamodules in favor of `K.RandomCrop` during training and `ExtractPatches` for val/test/predicting.

Refactor _RandomNCrop to RandomCrop + ExtractPatches

---

tests/models/test_copernicusfm.py

@robmarkcole encountered the following issue in #2707:
```
FAILED tests/models/test_copernicusfm.py::TestCopernicusFMBase::test_copernicusfm_variable - AssertionError: The input tensor is not within the configured range `[0.001, 510000000.0]`.
```
The problem is that random numbers between 0 and 1 are sometimes 0, which is outside the valid range. This PR adds 1 to ensure that it is always in range.

CopernicusFM: ensure test metadata is always within range

---

torchgeo/__init__.py

With a little luck (and a lot of planning), this next release may be 1.0.0 instead of 0.8.0 🙂

Bump TorchGeo version to 0.8.0.dev0

---

docs/user/alternatives.rst
docs/user/metrics/features.csv

Just discovered that DeepForest 0.X was TensorFlow-based and transitioned to PyTorch in 1.X: https://github.com/weecology/DeepForest/releases/tag/1.0.0
Should we continue to document historical support, or should we only document the latest backend? For example, TorchGeo is planning on switching from R-tree to geopandas.

Related Libraries: DeepForest used to support TensorFlow

---

torchgeo/samplers/batch.py
torchgeo/samplers/single.py

The `__iter__` method does not "return", it "yields". Change the docstring to account for this.

Samplers: yield instead of return

---

pyproject.toml

Silences the following CI warning in main:
```
../../../../../opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/lightning/pytorch/cli.py:52
/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/lightning/pytorch/cli.py:52: 
By default only one JsonargparseDeprecationWarning per type is shown. To see all warnings set environment
variable JSONARGPARSE_DEPRECATION_WARNINGS=all and to disable the warnings set
JSONARGPARSE_DEPRECATION_WARNINGS=off.
../../../../../opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/lightning/pytorch/cli.py:52
/opt/hostedtoolcache/Python/3.13.3/x64/lib/python3.13/site-packages/lightning/pytorch/cli.py:52: 
set_config_read_mode was deprecated in v4.39.0 and will be removed in v5.0.0. Optional config read modes
should …
```

CLI: silence jsonargparse deprecation warning

---

docs/conf.py

From RtD CI:
```
intersphinx inventory has moved: https://pytorch.org/vision/stable/objects.inv -> https://docs.pytorch.org/vision/stable/objects.inv
intersphinx inventory has moved: https://pytorch.org/docs/stable/objects.inv -> https://docs.pytorch.org/docs/stable/objects.inv
```

Docs: PyTorch docs site has moved

---

tests/conf/vhr10_ins_seg.yaml
tests/trainers/test_detection.py
tests/trainers/test_instance_segmentation.py
torchgeo/trainers/detection.py
torchgeo/trainers/instance_segmentation.py
torchgeo/trainers/utils.py

One of the wonderful surprises of torchvision's detector models is that a `GeneralizedRCNNTransform` gets added under the hood which defaults to ImageNet RGB mean/std normalize + dynamic resizing in the range of (800, 1333).
This PR fixes this by loading pretrained weights but overriding this transform to simply subtract 0 and divide by 1 which is a no-op and changes the dynamic resize to allow for a min/max input shape in the range of (1, 4096).
I attempted to simply replace `model.transform` with `nn.Identity()` but this doesn't work because the detection models pass multiple args to the transform which will throw an error.
Fixes #2749

ObjectDetection/InstanceSegmentationTask: fix support for non-RGB images

---

torchgeo/datamodules/naip.py

It's not every day you find a bug that has existed since TorchGeo 0.1: https://github.com/microsoft/torchgeo/blob/v0.1.0/torchgeo/datasets/naip.py#L154
Discovered while working on #2804.

NAIPChesapeakeDataModule: fix overlap between train and test

---

tests/datasets/test_geo.py
torchgeo/datasets/geo.py

Part of #2382 
Needed for applications like MultiMiner where we have a collection of satellite/drone imagery inputs at different times covering the same year. @MUYang99
Closes #2571

IntersectionDataset: support spatial-only intersection

---

docs/conf.py
tests/datasets/test_splits.py
torchgeo/datasets/splits.py

Now that we are using geopandas, we can easily support any arbitrary shapely Polygon: #2382
* roi_sampler no longer supports BoundingBox roi, use shapely Polygon instead
Loosely related to #1170 and #1190

roi_split: support arbitrary Polygon for roi

---

pyproject.toml
requirements/min-reqs.old
tests/conf/inria_dpt.yaml
tests/conf/inria_segformer.yaml
tests/conf/inria_upernet.yaml
tests/trainers/test_change.py
tests/trainers/test_regression.py
tests/trainers/test_segmentation.py
torchgeo/trainers/change.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py

This PR adds the newly supported SMP decoders (UPerNet, Segformer, DPT) for all dense output tasks (semantic seg, pixelwise regression, change detection).
In research papers I've been seeing a trend towards using UPerNet and DPT decoders to evaluate geospatial foundation models (particularly transformer-based ones) so we should enable users to do this within our trainers.

New SMP Decoders

---

docs/api/weights/agnostic.csv
tests/models/test_yolo.py
torchgeo/models/yolo.py

This PR adds the YOLO pretrained weights for SatSure's [core-dino](https://huggingface.co/gajeshladhar/core-dino) model. This model is a YOLO11x encoder-only pretrained using DINO on the [core-five](https://huggingface.co/datasets/gajeshladhar/core-five) dataset.
Note: I added an option to the `torchgeo.models.yolo` function to allow users to override the task type of a YOLO model. This basically means that if a model is pretrained for object detection (bbox), for example, you can pass `yolo(weights, task="segment")` to use the pretrained model for instance segmentation instead.

SatSure core-dino Model

---

docs/api/weights/sentinel2.csv
torchgeo/models/resnet.py

Adds the RN50 weights pretrained on the new SSL4Eco dataset using the SeCo-Eco method modified from the original SeCo method. This is from the CVPR Earthvision paper ["SSL4Eco: A Global Seasonal Dataset for Geospatial Foundation Models in Ecology", Plekhanova et al. (2025)](https://arxiv.org/abs/2504.18256).
Weights were extracted from the checkpoint and tweaked to be loadable with timm and torchvision resnet50 and rehosted to huggingface [here](https://huggingface.co/torchgeo/seco-eco).
cc: @PlekhanovaElena @drprojects @jdollinger-bit

Add SSL4Eco SeCo-Eco Weights

---

requirements/min-reqs.old

Failing minimum tests due to huggingface/safetensors#641, for now we can pin to older safetensors.

Fix minimum tests, avoid broken safetensors

---

docs/api/models.rst
docs/api/weights/atmospheric.csv
docs/api/weights/climate.csv
hubconf.py
pyproject.toml
requirements/min-reqs.old
requirements/models.txt
tests/models/test_api.py
tests/models/test_aurora.py
torchgeo/models/__init__.py
torchgeo/models/api.py
torchgeo/models/aurora.py

Adding the Aurora Atmospheric/Weather Forecasting models from https://github.com/microsoft/aurora!
See their [docs](https://microsoft.github.io/aurora/intro.html) and [paper](https://arxiv.org/abs/2405.13063) for more info!
cc: @wesselb @crisbodnar @megstanley

Aurora Atmospheric/Weather Forecasting Models

---

.github/dependabot.yml
requirements/min-reqs.old
requirements/models.txt
requirements/required.txt

Pip does not have an easy way to pin the version of setuptools used to build the project. Instead, it installs the latest version of setuptools into a separate build environment, ignoring the version of setuptools already present on the system. Since it doesn't work, let's reduce the number of dependabot PRs by removing this.
See https://discuss.python.org/t/pinning-build-dependencies/8363 for reference

Dependabot: don't track setuptools

---

docs/tutorials/earthquake_detection.ipynb

This PR fixes #2950 by renaming deprecated `SENTINEL1_ALL `to `ENTINEL1_GRD`.

Rename ResNet50 S1 weights in tutorial.

---

README.md

Fixes #2952
Adds a link to the TorchGeo Slack, and a link to join the Slack to the contributing section of the README.

Add Slack links to contributing section of README

---

.readthedocs.yaml
docs/conf.py
torchgeo/models/yolo.py

Something changed in an indirect dependency and now the RtD tests are failing with:
```
torchgeo/models/yolo.py:docstring of torchgeo.models.yolo.yolo:2: WARNING: py:class reference target not found: ultralytics.YOLO
```
I'm guessing one of our dependencies dropped a dependency on ultralytics and now it's no longer available in the environment.
This PR is a short-term fix. Long-term fixes include not linking to the ultralytics docs or removing the ultralytics dependency entirely.

RtD: linkage requires optional model deps

---

docs/tutorials/pretrained_weights.ipynb
docs/tutorials/trainers.ipynb

Fixes #2854 
this PR removes the use of PyTorch Lightning from the `pretrained_weights.ipynb` notebook to improve the tutorial's logical order
The changes consist of the following:
* The PyTorch Lightning dataloader and training module have been removed from `pretrained_weights.ipynb`
* Code to inspect the metadata of the pretrained weights has been added to the notebook
* Content regarding the Lightning Trainer has been moved to `trainer.ipynb`
No new tests are needed for this PR

Remove PyTorch Lightning from Pretrained Weights tutorial

---

docs/tutorials/pytorch.ipynb

Bug introduced in 0.7.1
TODO: figure out why CI didn't catch this
Fixes #2895

PyTorch Tutorial: download all split files

---

.github/dependabot.yml
requirements/required.txt

Follow-up to #2996 
Although our normal CI tests don't fail with 2.5.5, the tutorial tests fail due to installation of conflicting versions.

Deps: prevent lightning 2.5.5 from being used in CI
