torchgeo/torchgeo

conf/naipchesapeake.yaml
conf/task_defaults/naipchesapeake.yaml
torchgeo/trainers/__init__.py
torchgeo/trainers/naipchesapeake.py
train.py

I just converted the LandCover.AI trainer to NAIP + Chesapeake. Haven't yet tested this.
There's a lot of duplication between trainers at the moment. We can refactor that after adding a few more trainers.
Still need to add tests.

Add trainer for NAIP + Chesapeake

---

docs/requirements.txt
environment.yml
requirements.txt
setup.cfg
spack.yaml
tests/models/test_fccd.py
torchgeo/models/__init__.py
torchgeo/models/fccd.py

- Adds `FCEF`, `FCSiamConc`, `FCSiamDiff` to `torchgeo.models`.
- Adds `einops` as a dependency
- Added unit tests `tests/models/tests_fccd.py`
- Modified all models to work with any `t` (in the case of multitemporal change detection where `t>2`)
Example:
```python
import torch
from torchgeo.models import FCEF, FCSiamDiff, FCSiamConc
b, t, c, h, w = 2, 2, 3, 64, 64
x = torch.randn(b, t, c, h, w)
model = FCEF(in_channels=3, t=2, classes=2)
model(x)  # (b, classes, h, w)
model = FCSiamConc(in_channels=3, t=2, classes=2)
model(x)  # (b, classes, h, w)
model = FCSiamDiff(in_channels=3, t=2, classes=2)
model(x)  # (b, classes, h, w)
```
Reference:
- [Paper: "Fully Convolutional Siamese Networks for Change Detection", Daudt et al. (2018)](https://arxiv.org/abs/1810.08462)
- [Official author …

Add Fully Convolutional Change Detection (FCCD) models

---

tests/datasets/test_benin_cashews.py
tests/datasets/test_cv4a_kenya_crop_type.py
tests/datasets/test_spacenet.py
tests/datasets/test_utils.py
torchgeo/datasets/benin_cashews.py
torchgeo/datasets/cv4a_kenya_crop_type.py
torchgeo/datasets/cyclone.py
torchgeo/datasets/spacenet.py
torchgeo/datasets/utils.py

Add download_radiant_mlhub_collection

---

README.md
docs/index.rst
docs/user/contributing.rst

We should make it easy as possible for people to contribute. This PR adds a new section in the README to help new first-time contributors.
@ashnair1 am I missing anything in the pre-commit section? also, thanks again for the SpaceNet and pre-commit PRs!
@adamjstewart @isaaccorley, feel free to edit/suggest as you see fit. The name of the game is to reduce the friction between _anyone_ saying, "hey I could add < x > to torchgeo," and us merging a well formatted pull request.
Closes #158

Adding instructions for new contributors

---

docs/tutorials/benchmarking.ipynb
docs/tutorials/getting_started.ipynb
docs/tutorials/trainers.ipynb

Tutorials: use pip install torchgeo

---

tests/datasets/test_bigearthnet.py
torchgeo/datasets/resisc45.py
torchgeo/datasets/seco.py
torchgeo/datasets/ucmerced.py

0eadac4e2c9585012fb5123110cb8f44a133a6d6 configured black to run with `--skip-magic-trailing-comma`. This PR fixes some files that it missed via `pre-commit run --all-files`

Run black --skip-magic-trailing-comma

---

tests/models/test_rcf.py
torchgeo/models/rcf.py

Adding seed to RCF model

---

docs/api/models.rst
docs/conf.py
torchgeo/models/resnet.py

We somehow forgot to include this in the docs.

Add ResNet pre-trained models to the docs

---

docs/tutorials/benchmarking.ipynb
docs/tutorials/getting_started.ipynb
docs/tutorials/transforms.ipynb

Hi.
- removed unused imports in notebooks `{benchmarking,getting_started,indices,transforms}.ipynb`
- in `transforms.ipynb` fixed parameter `idx` range, previously _Index out of range_ error raised. Number of points in dataset is 16200

Edit tutorials notebooks

---

environment.yml
setup.cfg

Bumping torchvision dependency version to 0.10

---

tests/datasets/test_chesapeake.py
torchgeo/datasets/chesapeake.py

Implements the design from #99 for the rest of the Chesapeake datasets.

Chesapeake: support already downloaded zip files

---

.github/workflows/release.yaml
.github/workflows/tests.yaml

I don't think we need to test this on every PR. Only testing when we create a release branch should be sufficient.

Only test optional dataset deps on release branch

---

torchgeo/datasets/geo.py
torchgeo/datasets/utils.py

Mark features added in #144 as new

---

.github/labeler.yml
.github/workflows/labeler.yml

Closes #235 
See https://github.com/actions/labeler for documentation.

Use labeler bot to automatically label PRs

---

tests/datasets/test_advance.py
tests/datasets/test_benin_cashews.py
tests/datasets/test_bigearthnet.py
torchgeo/datasets/advance.py
torchgeo/datasets/benin_cashews.py
torchgeo/datasets/bigearthnet.py

Adds plotting for ADVANCE, BeninSmallHolderCashews and BigEarthNet datasets (#253)

Add plot method to ADVANCE, BeninSmallHolderCashews, and BigEarthNet datasets

---

tests/datasets/test_eurosat.py
torchgeo/datasets/eurosat.py

This PR fixes #396 by adding band selection to the dataset and adapting the plot method so that it only plots when the rgb indices are present.
Example plot:
<p float="left">
</p>

Add band selection to EuroSat and adapt plot method

---

.pre-commit-config.yaml

Update torch min version to 1.11.0 to match 9489b613722d190f855674aa85cd1907c0e26a5d

Update torch in mypy hook

---

torchgeo/datasets/utils.py

I'm honestly not sure why I added this in #134 but I think it's wrong. It doesn't really make much of a difference anyway.

Don't subtract microsecond from mint

---

.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml
setup.cfg

PyTorch 1.11 (released today) finally adds wheels for Python 3.10, so we should now be able to test it in TorchGeo.
Reboot of #243

Test on Python 3.10

---

docs/tutorials/benchmarking.ipynb
docs/tutorials/getting_started.ipynb

Tutorials: fix NAIP downloads

---

docs/api/non_geo_datasets.csv

Inria is a Semantic Segmentation dataset

Correct Inria task

---

.github/workflows/tests.yaml
requirements/required.old
requirements/required.txt

Got impatient and couldn't wait for dependabot. Hopefully this will fix our failing CI. May also need to pin GEOS in the conda install to fix the failing Windows CI.

Bump rasterio dep to v1.3.0

---

conf/cowc_counting.yaml
experiments/find_optimal_hyperparams.py
experiments/run_cowc_experiments.py
experiments/run_cowc_seed_experiments.py
tests/trainers/test_regression.py
torchgeo/trainers/regression.py

Original authors got RMSE: 0.657, MAE: 0.248 with ResCeption, I got RMSE: 0.597, MAE: 0.290 with ResNet-50
Optimal hyperparams are pre-trained ResNet-50 with a learning rate of 0.0001. Still need to run seed experiments though.

Add COWC counting experiment

---

.github/workflows/tests.yaml
tests/datasets/test_nwpu.py
tests/datasets/test_resisc45.py
tests/datasets/test_utils.py

https://github.com/markokr/rarfile/issues/72

Test rarfile on Windows

---

docs/tutorials/transforms.ipynb

Closes https://github.com/microsoft/torchgeo/issues/763

Fix transforms notebook

---

docs/conf.py
docs/tutorials/benchmarking.ipynb
docs/tutorials/custom_raster_dataset.ipynb
docs/tutorials/getting_started.ipynb
docs/tutorials/indices.ipynb
docs/tutorials/trainers.ipynb
docs/tutorials/transforms.ipynb

See https://github.com/spatialaudio/nbsphinx/issues/670

Tutorials: use ipython lexer

---

conf/inria.yaml
tests/conf/inria.yaml
torchgeo/datamodules/inria.py

- Fixed `ignore_index` setting. 
- Added plot function

Inria fixes

---

.pre-commit-config.yaml
environment.yml

Follow-up to #816 
I would love to delete these files someday so we don't have to track our deps in so many places...
@remtav

Update torchmetrics dep in other places

---

docs/api/non_geo_datasets.csv

Fix for missing number of classes.
TIL Github supports csv rendering :smile:

Fix ReforesTree entry

---

CITATION.cff
README.md

No idea if these keys are correct. Also need to update the README.

Citation: arXiv -> SIGSPATIAL

---

tests/conf/nasa_marine_debris.yaml
tests/trainers/test_detection.py
torchgeo/trainers/detection.py

And also change the model argument name for the object detection task:
detection_model -> model

Change argument name Object Detection Task

---

torchgeo/datasets/loveda.py

This is the only URL that looks like this.

LoveDA: fix URL formatting

---

train.py

Resolves #705 by adding CSVLogger to train.

Added CSVLogger

---

.github/workflows/tests.yaml

Hoping this fixes the failing minimum tests.

Update apt-get repository before install

---

requirements/required.txt
setup.cfg

Need to be updated in unison since smp pins timm.

Bump smp and timm deps

---

environment.yml
requirements/min.old
requirements/required.old
requirements/required.txt
setup.cfg
tests/trainers/conftest.py
torchgeo/datasets/openbuildings.py

#917 removes 2/3 of packaging imports, this PR removes the other 1/3. Once both are merged, we can remove our dependency on packaging and have one less thing to track.

Remove packaging dependency

---

torchgeo/datasets/usavars.py

Fix typo in usavars.py

---

.github/workflows/release.yaml
.github/workflows/tests.yaml
conf/bigearthnet.yaml
conf/byol.yaml
conf/chesapeake_cvpr.yaml
conf/cowc_counting.yaml
conf/cyclone.yaml
conf/inria.yaml
conf/landcoverai.yaml
conf/nasa_marine_debris.yaml
conf/resisc45.yaml
conf/so2sat.yaml
conf/spacenet1.yaml
docs/tutorials/pretrained_weights.ipynb
docs/tutorials/trainers.ipynb
pyproject.toml
setup.cfg
tests/datasets/test_geo.py
tests/test_train.py
torchgeo/__init__.py
torchgeo/datamodules/inria.py
torchgeo/datasets/__init__.py
torchgeo/datasets/cyclone.py
torchgeo/datasets/geo.py
torchgeo/datasets/usavars.py

0.4.0 release

---

environment.yml

Noticed some missing deps. This file isn't included in the sdist so it doesn't have to go in a release.

Conda: update environment.yml

---

.github/workflows/tests.yaml
requirements/docs.txt
requirements/min-cons.old
requirements/min-reqs.old
requirements/min.old

See https://github.com/pypa/pip/issues/11760

Constrain dependencies to avoid CI hang

---

docs/user/contributing.rst

Follow-up to #1058, forgot to update one section of the docs.

Update pyupgrade Python version support

---

.github/dependabot.yml
environment.yml
requirements/docs.txt
setup.cfg

Want to see if this fixes the broken version selection button.

Fix version selection button in docs

---

tests/trainers/test_classification.py
tests/trainers/test_regression.py

Tests: downloaded weights have different number of classes

---

setup.cfg

Lightning: add support for v2

---

evaluate.py
train.py

See:
* https://lightning.ai/pages/blog/training-compiled-pytorch-2.0-with-pytorch-lightning/
* https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html
This should hopefully make our benchmarking much quicker. Anyone want to benchmark the difference?
@isaaccorley you'll also want to add this to any other scripts you create for the pipeline.
@yichiac @shradhasehgal you'll want to use this to make benchmarking faster.

Use torch.compile if available

---

evaluate.py
train.py

Reverts microsoft/torchgeo#1225
Doesn't seem to work with the current Lightning version.

Revert "Use torch.compile if available"

---

docs/api/geo_datasets.csv

CDL is created using Landsat imagery.

CDL: fix documented data source

---

docs/conf.py

https://github.com/pyvista/pyvista/issues/4283

PyVista: fix intersphinx link

---

.github/workflows/tests.yaml
.pre-commit-config.yaml
environment.yml
requirements/min-reqs.old
setup.cfg
tests/datamodules/test_usavars.py
tests/datasets/test_benin_cashews.py
tests/datasets/test_cloud_cover.py
tests/datasets/test_cv4a_kenya_crop_type.py
tests/datasets/test_cyclone.py
tests/datasets/test_eddmaps.py
tests/datasets/test_gbif.py
tests/datasets/test_idtrees.py
tests/datasets/test_inaturalist.py
tests/datasets/test_landcoverai.py
tests/datasets/test_nasa_marine_debris.py
tests/datasets/test_openbuildings.py
tests/datasets/test_reforestree.py
tests/datasets/test_resisc45.py
tests/datasets/test_so2sat.py
tests/datasets/test_spacenet.py
tests/datasets/test_usavars.py
tests/datasets/test_utils.py
tests/datasets/test_vhr10.py
tests/datasets/test_western_usa_live_fuel_moisture.py
tests/datasets/test_zuericrop.py
tests/trainers/test_classification.py

I always forget to do this after changing min versions.

Update test minversions, pyvista min version

---

setup.cfg

We forgot to add these in #1237

Add upper bounds to hydra/omegaconf deps

---

torchgeo/trainers/classification.py
torchgeo/trainers/detection.py
torchgeo/trainers/regression.py
torchgeo/trainers/segmentation.py

This PR updates missing docstrings for the freeze parameters.

freeze_backbone and freeze_decoder docstrings update

---

tests/data/README.md

Use context managers and profiles.

Better example for writing fake test data

---

experiments/ssl4eo/download_l5_raw.sh
experiments/ssl4eo/download_l7_l1.sh
experiments/ssl4eo/download_l7_l2.sh
experiments/ssl4eo/download_l8_l1.sh
experiments/ssl4eo/download_l8_l2.sh
experiments/ssl4eo/sample_30.sh
experiments/ssl4eo/sample_60.sh

Add copyright info to download scripts

---

experiments/ssl4eo/download_ssl4eo.py

Found that a lot of these type hints were wrong.
@wangyi111

SSL4EO download script: fix type hints

---

experiments/ssl4eo/download_ssl4eo.py

Don't ignore warnings in download script

---

experiments/ssl4eo/compress_dataset.py

Fix compression range

---

torchgeo/datamodules/resisc45.py

Fix RESISC45 dataset stats

---

torchgeo/datasets/cdl.py
torchgeo/datasets/cms_mangrove_canopy.py

Baffled by how mypy didn't catch this...

Ensure that all plot methods return figure

---

torchgeo/datasets/l8biome.py

The dataset isn't for validating clouds, it's for validating the algorithms used to detect them.
@shradhasehgal

L8 Biome: clarify dataset description

---

experiments/ssl4eo/class_imbalance.py

The following are indices and ratios of classes in the raw data before class remapping. They are computed on the entire dataset, not just train.
Classes: https://www.mrlc.gov/data/legends/national-land-cover-database-class-legend-and-description
3 classes is > 50%, 14 classes is > 99%, > 13 classes is < 1% each
```
[52 82 71 42 41 81 90 43 21 11 22 95 31 23 24 12]
[2.23591849e-01 1.66210204e-01 1.49072528e-01 1.22050323e-01
9.18512419e-02 6.24648072e-02 4.49184440e-02 3.35255302e-02
2.72570401e-02 2.35152598e-02 1.69524364e-02 1.60176083e-02
1.01668220e-02 9.04227700e-03 3.26252100e-03 1.01104386e-04]
```
```
[52 82 71 42 41 81 90 43 21 11 22 95 31 23 24 12]
[2.27304921e-01 1.72705650e-01 1.45825401e-01 1.20547265e-01
9.16905776e-02 5.94298355e-02 4.39258032e-02 3.43628339e-02 …
```

Compute class imbalance

---

torchgeo/datamodules/l7irish.py
torchgeo/datamodules/l8biome.py
torchgeo/datamodules/ssl4eo_benchmark.py
torchgeo/datasets/ssl4eo_benchmark.py
torchgeo/transforms/transforms.py

Data Augmentations:
- SSL4EO Benchmark: Random Horizontal and Vertical flip with p=0.2 and Random Crop
- L8Biome: Random Horizontal and Vertical flip with p=0.2
- L7Irish: Random Horizontal and Vertical flip with p=0.2

Define data augmentations for benchmark tasks

---

torchgeo/datasets/nlcd.py

NLCD: support future product versions

---

.github/workflows/release.yaml
.github/workflows/style.yaml
.github/workflows/tests.yaml
.github/workflows/tutorials.yaml

Improve CI concurrency robustness

---

experiments/ssl4eo/delete_excess.py
experiments/ssl4eo/landsat/README.md
experiments/ssl4eo/landsat/delete_excess.sh

One more script I forgot to commit.

SSL4EO: Add script to delete excess files

---

torchgeo/datasets/usavars.py

Fix USA Vars

---

conf/ssl4eo_l_oli_tirs_toa_mocov2_resnet50.yaml
conf/ssl4eo_l_oli_tirs_toa_mocov2_vits16.yaml
conf/ssl4eo_l_oli_tirs_toa_simclr_resnet50.yaml
conf/ssl4eo_l_oli_tirs_toa_simclr_vits16.yaml

on oli_tirs_toa with a ResNet-50 and ViT-S backbone

Added pretraining config files for MoCo and SimCLR 

---

torchgeo/datasets/usavars.py

This PR moves the USAVars dataset to Huggingface @calebrob6

Move USAVars to Huggingface

---

pyproject.toml

Reverts #557 
Closes #544
See #544 for discussion

Remove upper bounds from dependencies

---

experiments/ssl4eo/sample_ssl4eo.py

Fixes a bug introduced in #1385. See https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.nlargest.html

SSL4EO: fix sampling script

---

torchgeo/datasets/l7irish.py
torchgeo/datasets/l8biome.py

The auto-detected default CRS does not work for all images, set an explicit default instead.

L7 Irish/L8 Biome: fix default CRS

---

experiments/ssl4eo/plot_example_predictions.py

This is the script I used to create the example prediction plot for L7 Irish, and could be easily modified to reproduce the plot for CDL.

Add script to plot example predictions

---

README.md

Update `SemanticSegmentationTask` signature in `README.md` after the 0.5 release

SemanticSegmentationTask Signature in README

---

torchgeo/datasets/oscd.py

Close https://github.com/microsoft/torchgeo/issues/1652

Format OSCD images to float

---

.github/labeler.yml

setup.cfg -> pyproject.toml
environment.yml -> /dev/null

labeler: dependency files have changed

---

experiments/ssl4eo/flops.py

SSL4EO: convert script from MiB to MB

---

tests/datasets/test_idtrees.py

Headless PyVista plots

---

pyproject.toml

@pioneerHitesh can you see if this fixes #1687?

pytest: ignore distutils usage in torchmetrics

---

docs/api/non_geo_datasets.csv

Fix formatting for BioMassters

---

torchgeo/datasets/agb_live_woody_density.py
torchgeo/datasets/astergdem.py
torchgeo/datasets/cdl.py
torchgeo/datasets/chesapeake.py
torchgeo/datasets/cms_mangrove_canopy.py
torchgeo/datasets/esri2020.py
torchgeo/datasets/eudem.py
torchgeo/datasets/globbiomass.py
torchgeo/datasets/l7irish.py
torchgeo/datasets/l8biome.py
torchgeo/datasets/nlcd.py
torchgeo/datasets/openbuildings.py

Follow-up to #1704. Only backporting to the release branch because this will be replaced by #1714 in 0.6.
@pioneerHitesh

Fix another path/root inconsistency

---

torchgeo/datasets/sustainbench_crop_yield.py

SustainBenchCropYield: fix download

---

.pre-commit-config.yaml

Update pre-commit cfg

---

.github/workflows/tests.yaml

Workaround until we get the workflow_run workflow running.

Debug coverage

---

.github/workflows/tutorials.yaml
docs/tutorials/transforms.ipynb

Same as #1827 but for our notebook tests.

CI: stable notebook dependency versions

---

torchgeo/datamodules/chesapeake.py
torchgeo/datamodules/spacenet.py
torchgeo/datasets/benin_cashews.py
torchgeo/datasets/bigearthnet.py
torchgeo/datasets/biomassters.py
torchgeo/datasets/cloud_cover.py
torchgeo/datasets/cowc.py
torchgeo/datasets/cyclone.py
torchgeo/datasets/etci2021.py
torchgeo/datasets/idtrees.py
torchgeo/datasets/inria.py
torchgeo/datasets/landcoverai.py
torchgeo/datasets/levircd.py
torchgeo/datasets/loveda.py
torchgeo/datasets/mapinwild.py
torchgeo/datasets/nasa_marine_debris.py
torchgeo/datasets/oscd.py
torchgeo/datasets/pastis.py
torchgeo/datasets/potsdam.py
torchgeo/datasets/seasonet.py
torchgeo/datasets/skippd.py
torchgeo/datasets/spacenet.py
torchgeo/datasets/ssl4eo_benchmark.py
torchgeo/datasets/usavars.py
torchgeo/losses/qr.py
torchgeo/models/rcf.py
torchgeo/samplers/batch.py
torchgeo/samplers/single.py
torchgeo/transforms/color.py

Mostly reverts #1783
Newer mypy changed a bunch of things, which broke PyTorch. But the latest PyTorch release fixed those things, so the changes in #1783 are no longer needed. Going back to the way things were.

Revert mypy changes

---

README.md

We are also a member of the PyTorch Ecosystem
Preview: https://github.com/adamjstewart/torchgeo/tree/readme/pytorch

README: add PyTorch badge

---

requirements/required.txt
tests/datasets/test_geo.py
torchgeo/datasets/geo.py

Implement deterministic GeoDataset

---

torchgeo/datasets/deepglobelandcover.py

DeepGlobeLandCover: document download steps

---

pyproject.toml

Not sure what's wrong with the ignore syntax, trying different things...

pytest: silence kornia warnings

---

README.md

One more badge for our community. The logo is not yet recognized but will work once https://github.com/simple-icons/simple-icons/pull/9259 is merged.
Also fixed the color of the Slack logo to match the brand guidelines: https://brand.slackhq.com/color
Thoughts on the order of these badges? The colors all clash a bit...

README: add Hugging Face badge

---

.pre-commit-config.yaml

Added pillow to `additional_dependencies` since they added type hints in the latest version.

Add pillow and update hooks

---

docs/user/contributing.rst

https://torchgeo.readthedocs.io/en/latest/user/contributing.html#i-o-benchmarking
https://torchgeo--2016.org.readthedocs.build/en/2016/user/contributing.html#i-o-benchmarking

Docs: fix I/O bench table

---

.github/workflows/tests.yaml

https://github.com/actions/setup-python/issues/813

CI: disable caching on macOS

---

README.md

Update CLI script for test

---

torchgeo/trainers/detection.py
torchgeo/trainers/segmentation.py

adds num_classes. - Number of prediction classes (including the background) to the ObjectDetectionTask docs,

Update num_classes parameter description in ObjectDetectionTask class

---

docs/api/non_geo_datasets.csv
torchgeo/datasets/patternnet.py

Closes #2093 
The Google Drive link was not working anymore. Contacted the first author and agreed on hosting on HF under CC 4.0

host PatternNet on HF

---

README.md

Fix CLI test demo script

---

torchgeo/datasets/resisc45.py

Copied the text from VHR-10, our only other .rar dataset.

RESISC45: document rarfile dependency

---

tests/datasets/test_agrifieldnet.py
torchgeo/datasets/agrifieldnet.py

AgriFieldNet: add download support

---

tests/datasets/test_south_africa_crop_type.py
torchgeo/datasets/south_africa_crop_type.py

South Africa Crop Type: add download support

---

.github/dependabot.yml
pyproject.toml
requirements/required.txt

Add support for lightning 2.4+

---

.github/workflows/tests.yaml
requirements/min-cons.old
tests/conf/seco_byol_1.yaml
tests/conf/seco_byol_2.yaml
tests/conf/seco_moco_1.yaml
tests/conf/seco_moco_2.yaml
tests/conf/seco_simclr_1.yaml
tests/conf/seco_simclr_2.yaml
torchgeo/datamodules/so2sat.py
torchgeo/datasets/utils.py

Many of these comments are for old versions of dependencies and no longer apply.

Remove workarounds and comments for outdated bugs

---

.github/dependabot.yml

Partially reverts #2250, closes #2255

Dependabot: don't update timm

---

torchgeo/datasets/rwanda_field_boundary.py

Rwanda Field Boundary: don't plot empty masks

---

docs/tutorials/custom_raster_dataset.ipynb
tests/samplers/test_batch.py
tests/samplers/test_single.py
torchgeo/samplers/single.py

In my previous pull requests, I changed an assertion at the last moment and saw this somehow got merged into main (I dont know why this test passed). I believe this change was wrong, hence the PR to revert it.

Bugfix: wrong test assertion

---

docs/user/alternatives.rst
docs/user/metrics/downloads.csv
docs/user/metrics/features.csv
docs/user/metrics/github.csv

@adamjstewart -- I was asked by @yotarazona to help on the issue #2335 
Closes #2335

Docs: scikit-eo is a new alternative library

---

docs/tutorials/getting_started.ipynb

Planetary Computer now requires all downloads to be signed.

Tutorials: sign NAIP download

---

torchgeo/models/dofa.py

Adds following class attributes to DOFA:
-  `embed_dim` 
- `depth`

DOFA: save parameters as instance attributes

---

tests/models/test_resnet.py
tests/models/test_swin.py
tests/models/test_vit.py

\# bands should match # input channels

Test model bands

---

.github/workflows/tests.yaml
requirements/datasets.txt
requirements/min-reqs.old

Hoping these changes solve our failing CI issues.
Closes #2427

Bump pyvista to deal with VTK 9.4 release

---

tests/datasets/test_ucmerced.py
torchgeo/datasets/ucmerced.py

UC Merced: redistribute split files on Hugging Face

---

torchgeo/datasets/chesapeake.py

Closes #2390
Dan moved lila datasets to new storage locations.

Update ChesapeakeCVPR link

---

docs/index.rst
docs/tutorials/torchgeo.ipynb

Still a WIP, but this is the last intro section for #2418

Add Introduction to TorchGeo tutorial

---

docs/tutorials/basic_usage.rst
docs/tutorials/contribute_datamodule.ipynb
docs/tutorials/custom_raster_dataset.ipynb
docs/tutorials/earth_surface_water.ipynb
docs/tutorials/indices.ipynb
docs/tutorials/trainers.ipynb

Want to give credit to the people who wrote our tutorials.

Add consistent author and copyright info to all tutorials

---

docs/api/datasets/non_geo_datasets.csv
tests/datasets/test_zuericrop.py
torchgeo/datasets/zuericrop.py

Closes #2496 
Got permission from the authors to redistribute the dataset on HF, and was told that the license is CC-BY-NC-4.0.

ZueriCrop: rehost on HF

---

torchgeo/datasets/bigearthnet.py

Remove unecessary if statement check that also did not check in root directory as mentioned in #2531

BigEarthNet: Remove unnecessary line

---

docs/tutorials/trainers.ipynb

Trainers tutorial: document where checkpoints are saved, how to get best model

---

torchgeo/datasets/reforestree.py

ReforesTree: skip images with missing mappings

---

torchgeo/datasets/ftw.py

Update FTW documentation

---

docs/tutorials/contribute_datamodule.ipynb

fix typo in contribute_datamodule

fix typo in contribute_datamodule

---

docs/tutorials/geospatial.ipynb

Clarifies satellite orbit types and their typical use cases in time-series applications.

Fix typo in geospatial tutorial

---

README.md

These were changed in v0.7.0, but we forgot to update the README.

README: update VHR-10, semantic segmentation examples

---

CITATION.cff
README.md

I was going to wait until it moved from "Just Accepted" to an official issue, but let's do this now. Not sure if it's worth updating arXiv or not. We should probably announce something on Slack to let people know about the new citation.

Update TorchGeo paper citation

---

torchgeo/datasets/ftw.py

Previously the FTW dataset has no ability to plot predictions in it's `plot` method. This PR fixes that.
Sample plots:

FTW Plot Predictions

---

docs/user/alternatives.rst
docs/user/metrics/downloads.csv
docs/user/metrics/features.csv
docs/user/metrics/github.csv

Closes #2727
I couldn't find statistics for PyPI total download counts. It looks like they don't publish those numbers anymore.

Add GeoDeep to docs

---

tests/datasets/test_gbif.py
torchgeo/datasets/gbif.py

- Relevant issue: https://github.com/microsoft/torchgeo/issues/2377
- Added plot method to gbif dataset.
- Added test case for the plot method
This is how it looks like

Plot Method Added to GBIF Dataset

---

tests/datasets/test_inaturalist.py
torchgeo/datasets/inaturalist.py

- Relevant issue: https://github.com/microsoft/torchgeo/issues/2377
- Added plot method to iNaturalist dataset.
- Added test case for the plot method
Using the dataset from test, this is how the plot looks like

Plot Method Added to iNaturalist Dataset

---

torchgeo/trainers/instance_segmentation.py

Adds #2560 to our new instance segmentation trainer, which was developed at the same time #2560 was.

InstanceSegmentationTask: denormalize images before plotting

---

tests/datasets/test_mmearth.py
torchgeo/datasets/mmearth.py

- Relevant issue: https://github.com/microsoft/torchgeo/issues/2377
- Added plot method to MMEarth dataset.
- Added test case for the plot method
Using the dataset from test, this is how the plot looks like

Plot Method Added to MMEarth Dataset

---

torchgeo/datasets/copernicus/pretrain.py

Same as #2766, this is the only dataset with `__iter__`

CopernicusPretrain: returns -> yields

---

docs/api/datamodules.rst

Closes https://github.com/microsoft/torchgeo/issues/2775

Add VHR10DataModule to docs

---

docs/api/datamodules.rst

Only other missing data module from the docs

Add SKIPP'D data module to the docs

---

tests/datasets/test_eurosat.py
torchgeo/datasets/eurosat.py

Download Eurosat split file if only image folder exists

---

.github/CODE_OF_CONDUCT.md
.github/CONTRIBUTING.md
.github/GOVERNANCE.md
.github/MAINTAINERS.md
.github/SECURITY.md
.github/SUPPORT.md
README.md

This governance model is based on [MVG](https://github.com/github/MVG).
This PR is for the TorchGeo Python library. There is a separate WIP repo for the TorchGeo Organization: https://github.com/adamjstewart/torchgeo-governance

Add formal governance

---

torchgeo/datasets/cdl.py

Updating the CDL dataset with the new 2024 data.

Add CDL 2024 data

---

torchgeo/models/unet.py

Fix FTW Bands
